/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as Beehiiv from "../../../../api";
import * as core from "../../../../core";

export const SegmentsListRequestOrderBy: core.serialization.Schema<
    serializers.SegmentsListRequestOrderBy.Raw,
    Beehiiv.SegmentsListRequestOrderBy
> = core.serialization.enum_(["created", "last_calculated"]);

export declare namespace SegmentsListRequestOrderBy {
    type Raw = "created" | "last_calculated";
}
