/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as beehiiv from "../../../../api";
import * as core from "../../../../core";
import { Segment } from "../../../types/Segment";

export const SegmentsGetPublicationsPublicationIdSegmentsSegmentIdResponse: core.serialization.ObjectSchema<
    serializers.SegmentsGetPublicationsPublicationIdSegmentsSegmentIdResponse.Raw,
    beehiiv.SegmentsGetPublicationsPublicationIdSegmentsSegmentIdResponse
> = core.serialization.object({
    data: Segment,
});

export declare namespace SegmentsGetPublicationsPublicationIdSegmentsSegmentIdResponse {
    interface Raw {
        data: Segment.Raw;
    }
}
