/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as beehiiv from "../../../../api";
import * as core from "../../../../core";

export const SubscriptionsPatchSubscriptionsBulkActionsBulkUpdateResponseData: core.serialization.ObjectSchema<
    serializers.SubscriptionsPatchSubscriptionsBulkActionsBulkUpdateResponseData.Raw,
    beehiiv.SubscriptionsPatchSubscriptionsBulkActionsBulkUpdateResponseData
> = core.serialization.object({
    subscriptionUpdateId: core.serialization.property("subscription_update_id", core.serialization.string().optional()),
});

export declare namespace SubscriptionsPatchSubscriptionsBulkActionsBulkUpdateResponseData {
    interface Raw {
        subscription_update_id?: string | null;
    }
}
