/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as Beehiiv from "../../../../api";
import * as core from "../../../../core";
import { SubscriptionsPutRequestSubscriptionsItemTier } from "./SubscriptionsPutRequestSubscriptionsItemTier";
import { SubscriptionsPutRequestSubscriptionsItemCustomFieldsItem } from "./SubscriptionsPutRequestSubscriptionsItemCustomFieldsItem";

export const SubscriptionsPutRequestSubscriptionsItem: core.serialization.ObjectSchema<
    serializers.SubscriptionsPutRequestSubscriptionsItem.Raw,
    Beehiiv.SubscriptionsPutRequestSubscriptionsItem
> = core.serialization.object({
    subscriptionId: core.serialization.property("subscription_id", core.serialization.string()),
    tier: SubscriptionsPutRequestSubscriptionsItemTier.optional(),
    unsubscribe: core.serialization.boolean().optional(),
    customFields: core.serialization.property(
        "custom_fields",
        core.serialization.list(SubscriptionsPutRequestSubscriptionsItemCustomFieldsItem).optional()
    ),
});

export declare namespace SubscriptionsPutRequestSubscriptionsItem {
    interface Raw {
        subscription_id: string;
        tier?: SubscriptionsPutRequestSubscriptionsItemTier.Raw | null;
        unsubscribe?: boolean | null;
        custom_fields?: SubscriptionsPutRequestSubscriptionsItemCustomFieldsItem.Raw[] | null;
    }
}
