/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as beehiiv from "../../../../api";
import * as core from "../../../../core";

export const SubscriptionsPostSubscriptionsRequestDoubleOptOverride: core.serialization.Schema<
    serializers.SubscriptionsPostSubscriptionsRequestDoubleOptOverride.Raw,
    beehiiv.SubscriptionsPostSubscriptionsRequestDoubleOptOverride
> = core.serialization.enum_(["on", "off", "not_set"]);

export declare namespace SubscriptionsPostSubscriptionsRequestDoubleOptOverride {
    type Raw = "on" | "off" | "not_set";
}
