/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as beehiiv from "../../../../api";
import * as core from "../../../../core";

export const SubscriptionsGetSubscriptionsRequestExpandItem: core.serialization.Schema<
    serializers.SubscriptionsGetSubscriptionsRequestExpandItem.Raw,
    beehiiv.SubscriptionsGetSubscriptionsRequestExpandItem
> = core.serialization.enum_(["stats", "custom_fields", "referrals"]);

export declare namespace SubscriptionsGetSubscriptionsRequestExpandItem {
    type Raw = "stats" | "custom_fields" | "referrals";
}
