/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as beehiiv from "../../../../api";
import * as core from "../../../../core";
import { Subscription } from "../../../types/Subscription";

export const SubscriptionsGetSubscriptionsResponse: core.serialization.ObjectSchema<
    serializers.SubscriptionsGetSubscriptionsResponse.Raw,
    beehiiv.SubscriptionsGetSubscriptionsResponse
> = core.serialization.object({
    data: core.serialization.list(Subscription),
    limit: core.serialization.number(),
    page: core.serialization.number(),
    totalResults: core.serialization.property("total_results", core.serialization.number()),
    totalPages: core.serialization.property("total_pages", core.serialization.number()),
});

export declare namespace SubscriptionsGetSubscriptionsResponse {
    interface Raw {
        data: Subscription.Raw[];
        limit: number;
        page: number;
        total_results: number;
        total_pages: number;
    }
}
