/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as Beehiiv from "../../../../api";
import * as core from "../../../../core";

export const SubscriptionsGetRequestExpandItem: core.serialization.Schema<
    serializers.SubscriptionsGetRequestExpandItem.Raw,
    Beehiiv.SubscriptionsGetRequestExpandItem
> = core.serialization.enum_(["stats", "custom_fields", "referrals"]);

export declare namespace SubscriptionsGetRequestExpandItem {
    type Raw = "stats" | "custom_fields" | "referrals";
}
