/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as Beehiiv from "../../../../api";
import * as core from "../../../../core";

export const SubscriptionsPutRequestSubscriptionsItemTier: core.serialization.Schema<
    serializers.SubscriptionsPutRequestSubscriptionsItemTier.Raw,
    Beehiiv.SubscriptionsPutRequestSubscriptionsItemTier
> = core.serialization.enum_(["free", "premium"]);

export declare namespace SubscriptionsPutRequestSubscriptionsItemTier {
    type Raw = "free" | "premium";
}
