// This file was auto-generated by Fern from our API Definition.

export const EmailBlastsListRequestExpandItem = {
    /**
     * Returns statistics about the email blast(s). */
    Stats: "stats",
} as const;
export type EmailBlastsListRequestExpandItem =
    (typeof EmailBlastsListRequestExpandItem)[keyof typeof EmailBlastsListRequestExpandItem];
