export { SegmentsGetPublicationsPublicationIdSegmentsRequest } from "./SegmentsGetPublicationsPublicationIdSegmentsRequest";
export { SegmentsGetPublicationsPublicationIdSegmentsSegmentIdResultsRequest } from "./SegmentsGetPublicationsPublicationIdSegmentsSegmentIdResultsRequest";
