/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as beehiiv from "../../../..";

/**
 * @example
 *     {}
 *
 * @example
 *     {
 *         type: beehiiv.SegmentsGetPublicationsPublicationIdSegmentsRequestType.Dynamic,
 *         status: beehiiv.SegmentsGetPublicationsPublicationIdSegmentsRequestStatus.Pending,
 *         limit: 1,
 *         page: 1,
 *         orderBy: beehiiv.SegmentsGetPublicationsPublicationIdSegmentsRequestOrderBy.Created,
 *         direction: beehiiv.SegmentsGetPublicationsPublicationIdSegmentsRequestDirection.Asc
 *     }
 *
 * @example
 *     {
 *         type: beehiiv.SegmentsGetPublicationsPublicationIdSegmentsRequestType.Dynamic,
 *         status: beehiiv.SegmentsGetPublicationsPublicationIdSegmentsRequestStatus.Pending,
 *         limit: 1,
 *         page: 1,
 *         orderBy: beehiiv.SegmentsGetPublicationsPublicationIdSegmentsRequestOrderBy.Created,
 *         direction: beehiiv.SegmentsGetPublicationsPublicationIdSegmentsRequestDirection.Asc
 *     }
 *
 * @example
 *     {
 *         type: beehiiv.SegmentsGetPublicationsPublicationIdSegmentsRequestType.Dynamic,
 *         status: beehiiv.SegmentsGetPublicationsPublicationIdSegmentsRequestStatus.Pending,
 *         limit: 1,
 *         page: 1,
 *         orderBy: beehiiv.SegmentsGetPublicationsPublicationIdSegmentsRequestOrderBy.Created,
 *         direction: beehiiv.SegmentsGetPublicationsPublicationIdSegmentsRequestDirection.Asc
 *     }
 *
 * @example
 *     {
 *         type: beehiiv.SegmentsGetPublicationsPublicationIdSegmentsRequestType.Dynamic,
 *         status: beehiiv.SegmentsGetPublicationsPublicationIdSegmentsRequestStatus.Pending,
 *         limit: 1,
 *         page: 1,
 *         orderBy: beehiiv.SegmentsGetPublicationsPublicationIdSegmentsRequestOrderBy.Created,
 *         direction: beehiiv.SegmentsGetPublicationsPublicationIdSegmentsRequestDirection.Asc
 *     }
 *
 * @example
 *     {
 *         type: beehiiv.SegmentsGetPublicationsPublicationIdSegmentsRequestType.Dynamic,
 *         status: beehiiv.SegmentsGetPublicationsPublicationIdSegmentsRequestStatus.Pending,
 *         limit: 1,
 *         page: 1,
 *         orderBy: beehiiv.SegmentsGetPublicationsPublicationIdSegmentsRequestOrderBy.Created,
 *         direction: beehiiv.SegmentsGetPublicationsPublicationIdSegmentsRequestDirection.Asc
 *     }
 */
export interface SegmentsGetPublicationsPublicationIdSegmentsRequest {
    /**
     * Optionally filter the results by the segment's type.
     */
    type?: beehiiv.SegmentsGetPublicationsPublicationIdSegmentsRequestType;
    /**
     * Optionally filter the results by the segment's status.
     */
    status?: beehiiv.SegmentsGetPublicationsPublicationIdSegmentsRequestStatus;
    /**
     * A limit on the number of objects to be returned. The limit can range between 1 and 100, and the default is 10.
     */
    limit?: number;
    /**
     * Pagination returns the results in pages. Each page contains the number of results specified by the `limit` (default: 10).<br>If not specified, results 1-10 from page 1 will be returned.
     */
    page?: number;
    /**
     * The field that the results are sorted by. Defaults to created<br> `created` - The time in which the segment was first created.<br> `last_calculated` - The time that the segment last completed calculation. Measured in seconds since the Unix epoch.
     */
    orderBy?: beehiiv.SegmentsGetPublicationsPublicationIdSegmentsRequestOrderBy;
    /**
     * The direction that the results are sorted in. Defaults to asc<br> `asc` - Ascending, sorts from smallest to largest.<br> `desc` - Descending, sorts from largest to smallest.
     */
    direction?: beehiiv.SegmentsGetPublicationsPublicationIdSegmentsRequestDirection;
}
