/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The new status value to apply to these subscription IDs
 */
export type SubscriptionsPatchSubscriptionsBulkUpdateStatusRequestNewStatus = "active" | "inactive";

export const SubscriptionsPatchSubscriptionsBulkUpdateStatusRequestNewStatus = {
    Active: "active",
    Inactive: "inactive",
} as const;
