/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as beehiiv from "../../..";

export interface SubscriptionsPatchSubscriptionsBulkActionsBulkUpdateRequestSubscriptionsItem {
    /** The prefixed subscription ID */
    subscriptionId: string;
    /** The Tier of the Subscription (not required) */
    tier?: beehiiv.SubscriptionsPatchSubscriptionsBulkActionsBulkUpdateRequestSubscriptionsItemTier;
    /** A boolean value specifying whether to unsubscribe this subscription from the publication (not required) */
    unsubscribe?: boolean;
    /** An array of custom field objects to update */
    customFields?: beehiiv.SubscriptionsPatchSubscriptionsBulkActionsBulkUpdateRequestSubscriptionsItemCustomFieldsItem[];
}
