/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type SubscriptionsGetSubscriptionsRequestDirection = "asc" | "desc";

export const SubscriptionsGetSubscriptionsRequestDirection = {
    Asc: "asc",
    Desc: "desc",
} as const;
