/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as beehiiv from "../../..";

/**
 * The requested subscription object
 */
export interface SubscriptionsGetSubscriptionsEmailResponse {
    data: beehiiv.Subscription;
}
