/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as beehiiv from "../../../../api";
import * as core from "../../../../core";
import { CustomFieldsGetPublicationsPublicationIdCustomFieldsIdResponseDataKind } from "./CustomFieldsGetPublicationsPublicationIdCustomFieldsIdResponseDataKind";

export const CustomFieldsGetPublicationsPublicationIdCustomFieldsIdResponseData: core.serialization.ObjectSchema<
    serializers.CustomFieldsGetPublicationsPublicationIdCustomFieldsIdResponseData.Raw,
    beehiiv.CustomFieldsGetPublicationsPublicationIdCustomFieldsIdResponseData
> = core.serialization.object({
    id: core.serialization.string().optional(),
    display: core.serialization.string().optional(),
    kind: CustomFieldsGetPublicationsPublicationIdCustomFieldsIdResponseDataKind.optional(),
    created: core.serialization.number().optional(),
});

export declare namespace CustomFieldsGetPublicationsPublicationIdCustomFieldsIdResponseData {
    interface Raw {
        id?: string | null;
        display?: string | null;
        kind?: CustomFieldsGetPublicationsPublicationIdCustomFieldsIdResponseDataKind.Raw | null;
        created?: number | null;
    }
}
