/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as beehiiv from "../../../../api";
import * as core from "../../../../core";

export const CustomFieldsDeletePublicationsPublicationIdCustomFieldsResponse: core.serialization.ObjectSchema<
    serializers.CustomFieldsDeletePublicationsPublicationIdCustomFieldsResponse.Raw,
    beehiiv.CustomFieldsDeletePublicationsPublicationIdCustomFieldsResponse
> = core.serialization.object({
    message: core.serialization.string().optional(),
});

export declare namespace CustomFieldsDeletePublicationsPublicationIdCustomFieldsResponse {
    interface Raw {
        message?: string | null;
    }
}
