/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as Beehiiv from "../../../../api";
import * as core from "../../../../core";
import { CustomFieldsGetResponseDataItemKind } from "./CustomFieldsGetResponseDataItemKind";

export const CustomFieldsGetResponseDataItem: core.serialization.ObjectSchema<
    serializers.CustomFieldsGetResponseDataItem.Raw,
    Beehiiv.CustomFieldsGetResponseDataItem
> = core.serialization.object({
    id: core.serialization.string().optional(),
    kind: CustomFieldsGetResponseDataItemKind.optional(),
    display: core.serialization.string().optional(),
    created: core.serialization.number().optional(),
});

export declare namespace CustomFieldsGetResponseDataItem {
    interface Raw {
        id?: string | null;
        kind?: CustomFieldsGetResponseDataItemKind.Raw | null;
        display?: string | null;
        created?: number | null;
    }
}
