/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         tags: ["Premium", "Basic"]
 *     }
 */
export interface SubscriptionTagsCreateRequest {
    /** Tags that can be used to group subscribers */
    tags?: string[];
}
