export { AutomationJourneysGetPublicationsPublicationIdAutomationsAutomationIdJourneysRequest } from "./AutomationJourneysGetPublicationsPublicationIdAutomationsAutomationIdJourneysRequest";
export { AutomationJourneysPostPublicationsPublicationIdAutomationsAutomationIdJourneysRequest } from "./AutomationJourneysPostPublicationsPublicationIdAutomationsAutomationIdJourneysRequest";
