/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type SegmentsGetPublicationsPublicationIdSegmentsRequestType = "dynamic" | "static" | "manual" | "all";

export const SegmentsGetPublicationsPublicationIdSegmentsRequestType = {
    Dynamic: "dynamic",
    Static: "static",
    Manual: "manual",
    All: "all",
} as const;
