/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type SegmentsListRequestOrderBy = "created" | "last_calculated";

export const SegmentsListRequestOrderBy = {
    Created: "created",
    LastCalculated: "last_calculated",
} as const;
