/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The tier for this subscription.
 */
export type BulkSubscriptionsCreateRequestTier = "free" | "premium";
export const BulkSubscriptionsCreateRequestTier = {
    Free: "free",
    Premium: "premium",
} as const;
