/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The response containing the import ID
 */
export interface BulkSubscriptionCreateResponse {
    /** The result of the create request */
    message: string;
    /** The database ID of the import object created from the Bulk Subscription Create request */
    import_id: string;
}
