/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Beehiiv from "..";

export interface Automation {
    /** A unique prefixed id of the automation */
    id: string;
    status: Beehiiv.AutomationStatus;
    name: string;
    description?: string;
}
