/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type AutomationJourneyStatus = "initiated" | "running" | "completed" | "failed";

export const AutomationJourneyStatus = {
    Initiated: "initiated",
    Running: "running",
    Completed: "completed",
    Failed: "failed",
} as const;
