/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as beehiiv from "..";

/**
 * The top level error response.
 */
export interface Error_ {
    status: string;
    statusText: string;
    errors: beehiiv.ErrorErrorsItem[];
}
