// This file was auto-generated by Fern from our API Definition.

/** The platform that the post is or will be published to. */
export const PostPlatform = {
    Web: "web",
    Email: "email",
    Both: "both",
} as const;
export type PostPlatform = (typeof PostPlatform)[keyof typeof PostPlatform];
