// This file was auto-generated by Fern from our API Definition.

import type * as Beehiiv from "../index.js";

export interface Post {
    /** The prefixed post id */
    id: Beehiiv.PostId;
    /** The subtitle displayed in web views */
    subtitle: string;
    /** The title displayed in web views */
    title: string;
    /** An array of author names */
    authors: string[];
    /** The time the post was created. Measured in seconds since the Unix epoch */
    created: number;
    /** The status of the post.<br>`draft` - not been scheduled.<br>`confirmed` - The post will be active after the `scheduled_at`.<br>`archived` - The post is no longer active. */
    status: Beehiiv.PostStatus;
    /** The time the post was set to be published. Measured in seconds since the Unix epoch */
    publish_date?: number;
    /** The time displayed in place of the `publish_date`. Measured in seconds since the Unix epoch */
    displayed_date?: number;
    /** A flag to indicate if a split test was done. Only applicable to email posts. */
    split_tested: boolean;
    /** The email subject line. In cases of A/B Testing, this will be adjusted to the winning subject line. */
    subject_line: string;
    /** The email preview text */
    preview_text: string;
    /** The web slug where this post can be accessed. */
    slug: string;
    /** The URL of the thumbnail. Defaults to the Publication logo if not set. */
    thumbnail_url: string;
    /** The full URL where this post can be accessed on the web. Only applicable if the platform is `web` or `both`. */
    web_url: string;
    /** The audience that the post is available to on the web. Only applicable if the platform is `web` or `both`. */
    audience: Beehiiv.PostAudience;
    /** The platform that the post is or will be published to. */
    platform: Beehiiv.PostPlatform;
    /** All content tags that were associated with the post. */
    content_tags: string[];
    /** Meta tag description for the post, called SEO Description in the admin UI */
    meta_default_description?: string;
    /** meta tag title for the post, called SEO Title in the admin UI */
    meta_default_title?: string;
    content?: Beehiiv.PostContent;
    stats?: Beehiiv.PostStats;
    /** A flag to indicate if the post is hidden from the website feed. */
    hidden_from_feed: boolean;
}
