// This file was auto-generated by Fern from our API Definition.

/** The acquisition channel */
export const SubscriptionExpandedTagsUtmChannel = {
    Empty: "",
    Website: "website",
    Import: "import",
    Embed: "embed",
    Api: "api",
    Referral: "referral",
    Recommendation: "recommendation",
    MagicLink: "magic_link",
    Boost: "boost",
    BoostSend: "boost_send",
    BoostDirectLink: "boost_direct_link",
    Integration: "integration",
    Product: "product",
} as const;
export type SubscriptionExpandedTagsUtmChannel =
    (typeof SubscriptionExpandedTagsUtmChannel)[keyof typeof SubscriptionExpandedTagsUtmChannel];
