/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as beehiiv from "../../../../api";
import * as core from "../../../../core";
import { BulkSubscriptionUpdatesGetPublicationsPublicationIdSubcriptionUpdatesResponseDataItem } from "./BulkSubscriptionUpdatesGetPublicationsPublicationIdSubcriptionUpdatesResponseDataItem";

export const BulkSubscriptionUpdatesGetPublicationsPublicationIdSubcriptionUpdatesResponse: core.serialization.ObjectSchema<
    serializers.BulkSubscriptionUpdatesGetPublicationsPublicationIdSubcriptionUpdatesResponse.Raw,
    beehiiv.BulkSubscriptionUpdatesGetPublicationsPublicationIdSubcriptionUpdatesResponse
> = core.serialization.object({
    data: core.serialization
        .list(BulkSubscriptionUpdatesGetPublicationsPublicationIdSubcriptionUpdatesResponseDataItem)
        .optional(),
});

export declare namespace BulkSubscriptionUpdatesGetPublicationsPublicationIdSubcriptionUpdatesResponse {
    interface Raw {
        data?: BulkSubscriptionUpdatesGetPublicationsPublicationIdSubcriptionUpdatesResponseDataItem.Raw[] | null;
    }
}
