/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type CustomFieldsPostPublicationsPublicationIdCustomFieldsRequestKind =
    | "string"
    | "integer"
    | "boolean"
    | "date"
    | "datetime";

export const CustomFieldsPostPublicationsPublicationIdCustomFieldsRequestKind = {
    String: "string",
    Integer: "integer",
    Boolean: "boolean",
    Date: "date",
    Datetime: "datetime",
} as const;
