/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Beehiiv from "../../..";

export interface CustomFieldsGetResponseDataItem {
    id?: string;
    kind?: Beehiiv.CustomFieldsGetResponseDataItemKind;
    display?: string;
    created?: number;
}
