/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as beehiiv from "../../..";

export interface CustomFieldsPatchPublicationsPublicationIdCustomFieldsIdResponseData {
    id?: string;
    display?: string;
    kind?: beehiiv.CustomFieldsPatchPublicationsPublicationIdCustomFieldsIdResponseDataKind;
    created?: number;
}
