/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Beehiiv from "../../../index";

export interface CustomFieldsGetResponseData {
    id?: string;
    display?: string;
    kind?: Beehiiv.CustomFieldsGetResponseDataKind;
    created?: number;
}
