// This file was auto-generated by Fern from our API Definition.

import type * as Beehiiv from "../../../../index.js";

/**
 * @example
 *     {
 *         limit: 10
 *     }
 *
 * @example
 *     {
 *         limit: 10,
 *         cursor: "eyJ0aW1lc3RhbXAiOiIyMDI0LTA3LTAyVDE3OjMwOjAwLjAwMDAwMFoifQ=="
 *     }
 *
 * @example
 *     {
 *         email: "clark@dailyplanet.com",
 *         page: 1,
 *         limit: 10
 *     }
 */
export interface SubscriptionsListRequest {
    /** Optional list of expandable objects.<br>`subscription_premium_tiers ` - Returns an array of tiers the subscription is associated with.<br>`referrals` - Returns an array of subscriptions with limited data - `id`, `email`, and `status`. These are the subscriptions that were referred by this subscription.<br>`stats` - Returns statistics about the subscription(s).<br>`custom_fields` - Returns an array of custom field values that have been set on the subscription. */
    "expand[]"?: Beehiiv.SubscriptionsListRequestExpandItem | Beehiiv.SubscriptionsListRequestExpandItem[];
    /** Optionally filter the results by a status */
    status?: Beehiiv.SubscriptionsListRequestStatus;
    /** Optionally filter the results by a their tier */
    tier?: Beehiiv.SubscriptionsListRequestTier;
    /** Optionally filter the results by one or multiple premium tiers */
    "premium_tiers[]"?: string | string[];
    /** Optionally filter the results by one or multiple premium tier ids */
    "premium_tier_ids[]"?: string | string[];
    /** A limit on the number of objects to be returned. The limit can range between 1 and 100, and the default is 10. */
    limit?: number;
    /** **Cursor-based pagination (recommended)**: Use this opaque cursor token to fetch the next page of results. When provided, pagination will use cursor-based method which is more efficient and consistent than offset-based pagination. See the [Pagination Guide](/welcome/pagination) for more details. */
    cursor?: string;
    /** **Offset-based pagination (deprecated)**: Page number for offset-based pagination. This method is deprecated and limited to 100 pages maximum. Please migrate to cursor-based pagination using the `cursor` parameter. If not specified, results 1-10 from page 1 will be returned. See the [Pagination Guide](/welcome/pagination) for migration guidance. */
    page?: number;
    /** Optional email address to find a subscription.<br>This param must be an exact match and is case insensitive. */
    email?: string;
    /** The field that the results are sorted by. Defaults to created<br> `created` - The time in which the subscription was first created.<br> */
    order_by?: Beehiiv.SubscriptionsListRequestOrderBy;
    /** The direction that the results are sorted in. Defaults to asc<br> `asc` - Ascending, sorts from smallest to largest.<br> `desc` - Descending, sorts from largest to smallest. */
    direction?: Beehiiv.RequestDirection;
    /** Optional date entry (in the format YYYY/MM/DD) that filters returned subscriptions by their creation date. */
    creation_date?: string;
}
