/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Beehiiv from "../../api";
import * as core from "../../core";
import { CustomFieldKind } from "./CustomFieldKind";

export const CustomField: core.serialization.ObjectSchema<serializers.CustomField.Raw, Beehiiv.CustomField> =
    core.serialization.object({
        name: core.serialization.string().optional(),
        kind: CustomFieldKind.optional(),
        value: core.serialization.string().optional(),
    });

export declare namespace CustomField {
    interface Raw {
        name?: string | null;
        kind?: CustomFieldKind.Raw | null;
        value?: string | null;
    }
}
