/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as beehiiv from "../../api";
import * as core from "../../core";
import { ErrorErrorsItem } from "./ErrorErrorsItem";

export const Error_: core.serialization.ObjectSchema<serializers.Error_.Raw, beehiiv.Error_> =
    core.serialization.object({
        status: core.serialization.string(),
        statusText: core.serialization.string(),
        errors: core.serialization.list(ErrorErrorsItem),
    });

export declare namespace Error_ {
    interface Raw {
        status: string;
        statusText: string;
        errors: ErrorErrorsItem.Raw[];
    }
}
