/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as beehiiv from "../../api";
import * as core from "../../core";
import { MilestoneRewardType } from "./MilestoneRewardType";

export const MilestoneReward: core.serialization.ObjectSchema<
    serializers.MilestoneReward.Raw,
    beehiiv.MilestoneReward
> = core.serialization.object({
    id: core.serialization.string(),
    name: core.serialization.string(),
    description: core.serialization.string(),
    imageUrl: core.serialization.property("image_url", core.serialization.string()),
    type: MilestoneRewardType,
});

export declare namespace MilestoneReward {
    interface Raw {
        id: string;
        name: string;
        description: string;
        image_url: string;
        type: MilestoneRewardType.Raw;
    }
}
