/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Beehiiv from "../../api/index";
import * as core from "../../core";

export const PostContentFree: core.serialization.ObjectSchema<
    serializers.PostContentFree.Raw,
    Beehiiv.PostContentFree
> = core.serialization.object({
    web: core.serialization.string().optional(),
    email: core.serialization.string().optional(),
    rss: core.serialization.string().optional(),
});

export declare namespace PostContentFree {
    interface Raw {
        web?: string | null;
        email?: string | null;
        rss?: string | null;
    }
}
