/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as beehiiv from "../../api";
import * as core from "../../core";

export const PostAudience: core.serialization.Schema<serializers.PostAudience.Raw, beehiiv.PostAudience> =
    core.serialization.enum_(["free", "premium", "both"]);

export declare namespace PostAudience {
    type Raw = "free" | "premium" | "both";
}
