/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Beehiiv from "../../api/index";
import * as core from "../../core";

export const PublicationStatsActiveSubscriptions: core.serialization.Schema<
    serializers.PublicationStatsActiveSubscriptions.Raw,
    Beehiiv.PublicationStatsActiveSubscriptions
> = core.serialization.undiscriminatedUnion([core.serialization.number(), core.serialization.boolean()]);

export declare namespace PublicationStatsActiveSubscriptions {
    type Raw = number | boolean;
}
