/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as beehiiv from "../../..";

export interface AutomationsGetPublicationsPublicationIdAutomationsAutomationIdResponse {
    data?: beehiiv.Automation;
}
