/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as beehiiv from "../../../../api";
import * as core from "../../../../core";

export const AutomationJourneysPostPublicationsPublicationIdAutomationsAutomationIdJourneysRequestDoubleOptOverride: core.serialization.Schema<
    serializers.AutomationJourneysPostPublicationsPublicationIdAutomationsAutomationIdJourneysRequestDoubleOptOverride.Raw,
    beehiiv.AutomationJourneysPostPublicationsPublicationIdAutomationsAutomationIdJourneysRequestDoubleOptOverride
> = core.serialization.enum_(["on", "off", "not_set"]);

export declare namespace AutomationJourneysPostPublicationsPublicationIdAutomationsAutomationIdJourneysRequestDoubleOptOverride {
    type Raw = "on" | "off" | "not_set";
}
