/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as beehiiv from "../../../../api";
import * as core from "../../../../core";

export const AutomationJourneysGetPublicationsPublicationIdAutomationsAutomationIdJourneysRequestStatus: core.serialization.Schema<
    serializers.AutomationJourneysGetPublicationsPublicationIdAutomationsAutomationIdJourneysRequestStatus.Raw,
    beehiiv.AutomationJourneysGetPublicationsPublicationIdAutomationsAutomationIdJourneysRequestStatus
> = core.serialization.enum_(["in_progress", "completed", "exited_early", "all"]);

export declare namespace AutomationJourneysGetPublicationsPublicationIdAutomationsAutomationIdJourneysRequestStatus {
    type Raw = "in_progress" | "completed" | "exited_early" | "all";
}
