/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type PatchPublicationsPublicationIdTiersTierIdRequestPricesAttributesItemCurrency =
    | "usd"
    | "aud"
    | "cad"
    | "eur"
    | "inr"
    | "brl";

export const PatchPublicationsPublicationIdTiersTierIdRequestPricesAttributesItemCurrency = {
    Usd: "usd",
    Aud: "aud",
    Cad: "cad",
    Eur: "eur",
    Inr: "inr",
    Brl: "brl",
} as const;
