/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type PatchPublicationsPublicationIdTiersTierIdRequestPricesAttributesItemInterval = "month" | "year";

export const PatchPublicationsPublicationIdTiersTierIdRequestPricesAttributesItemInterval = {
    Month: "month",
    Year: "year",
} as const;
