// This file was auto-generated by Fern from our API Definition.

export const TierPriceCurrency = {
    Usd: "usd",
    Aud: "aud",
    Cad: "cad",
    Eur: "eur",
    Inr: "inr",
    Brl: "brl",
} as const;
export type TierPriceCurrency = (typeof TierPriceCurrency)[keyof typeof TierPriceCurrency];
