/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type TierPriceInterval = "month" | "quarter" | "year" | "one_time" | "donation";
export const TierPriceInterval = {
    Month: "month",
    Quarter: "quarter",
    Year: "year",
    OneTime: "one_time",
    Donation: "donation",
} as const;
