// This file was auto-generated by Fern from our API Definition.

import type * as Beehiiv from "../../../index.js";

export interface TierPricesAttributesItem {
    currency: Beehiiv.TierPriceCurrency;
    amount_cents: number;
    enabled?: boolean;
    interval: Beehiiv.TierPriceInterval;
    interval_display?: string;
    cta?: string;
    features?: string[];
}
