/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The status of the update
 */
export type BulkSubscriptionUpdatesGetPublicationsPublicationIdSubcriptionUpdatesIdResponseDataStatus =
    | "pending"
    | "processing"
    | "complete"
    | "failed";

export const BulkSubscriptionUpdatesGetPublicationsPublicationIdSubcriptionUpdatesIdResponseDataStatus = {
    Pending: "pending",
    Processing: "processing",
    Complete: "complete",
    Failed: "failed",
} as const;
