/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Beehiiv from "../../..";

export interface BulkSubscriptionUpdatesListResponse {
    /** An array of Subscription Update objects */
    data?: Beehiiv.BulkSubscriptionUpdatesListResponseDataItem[];
}
