// This file was auto-generated by Fern from our API Definition.

/** The status of the update */
export const BulkSubscriptionUpdatesGetResponseDataStatus = {
    Pending: "pending",
    Processing: "processing",
    Complete: "complete",
    Failed: "failed",
} as const;
export type BulkSubscriptionUpdatesGetResponseDataStatus =
    (typeof BulkSubscriptionUpdatesGetResponseDataStatus)[keyof typeof BulkSubscriptionUpdatesGetResponseDataStatus];
