/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as beehiiv from "../../..";

export interface BulkSubscriptionUpdatesGetPublicationsPublicationIdSubcriptionUpdatesIdResponseData {
    /** The ID of the update object */
    id?: string;
    /** The type of update (status or bulk) */
    type?: beehiiv.BulkSubscriptionUpdatesGetPublicationsPublicationIdSubcriptionUpdatesIdResponseDataType;
    /** The parameters passed in for the update */
    params?: string;
    /** The status of the update */
    status?: beehiiv.BulkSubscriptionUpdatesGetPublicationsPublicationIdSubcriptionUpdatesIdResponseDataStatus;
    /** The publication ID associated with this update */
    publicationId?: string;
    /** If the job as a whole fails, this will detail the errors encountered */
    failureReason?: string;
    /** The timestamp of the job's completion */
    completed?: number;
    /** The timestamp of the job's creation */
    created?: number;
    /** The timestamp of the job's update */
    updated?: number;
    /** An array of errors encountered for individual updates within the job */
    errorLog?: string[];
}
