/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Beehiiv from "../../../index.js";

export interface BaseBlock {
    /** Optional styling for borders, spacing, colors, etc. */
    visual_settings?: Beehiiv.VisualSettings;
    /** Optional rules for when/where this block is shown. */
    visibility_settings?: Beehiiv.VisibilitySettings;
}
