// This file was auto-generated by Fern from our API Definition.

/** The level of the header. */
export const HeadingLevel = {
    HeadingOne: "1",
    HeadingTwo: "2",
    HeadingThree: "3",
    HeadingFour: "4",
    HeadingFive: "5",
    HeadingSix: "6",
} as const;
export type HeadingLevel = (typeof HeadingLevel)[keyof typeof HeadingLevel];
