/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Beehiiv from "../../../index.js";

export interface HtmlBlock extends Beehiiv.BaseBlock {
    /** The raw HTML content. */
    html: string;
}
