/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type PostsGetPostsPostIdRequestExpandItem =
    | "stats"
    | "free_web_content"
    | "free_email_content"
    | "free_rss_content"
    | "premium_web_content"
    | "premium_email_content";

export const PostsGetPostsPostIdRequestExpandItem = {
    Stats: "stats",
    FreeWebContent: "free_web_content",
    FreeEmailContent: "free_email_content",
    FreeRssContent: "free_rss_content",
    PremiumWebContent: "premium_web_content",
    PremiumEmailContent: "premium_email_content",
} as const;
