// This file was auto-generated by Fern from our API Definition.

import type * as Beehiiv from "../../../index.js";

export interface PostsAggregateStatsResponse {
    data: Beehiiv.PostsAggregateStatsResponseStats;
}
