/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type PostsGetPostsRequestHiddenFromFeed = "all" | "true" | "false";

export const PostsGetPostsRequestHiddenFromFeed = {
    All: "all",
    True: "true",
    False: "false",
} as const;
