// This file was auto-generated by Fern from our API Definition.

import type * as Beehiiv from "../../../index.js";

export interface PostEmailRecipients {
    tier_ids?: string[];
    include_segment_ids?: Beehiiv.SegmentId[];
    exclude_segment_ids?: Beehiiv.SegmentId[];
}
