// This file was auto-generated by Fern from our API Definition.

export const PostSocialShare = {
    CommentsAndLikesOnly: "comments_and_likes_only",
    WithCommentsAndLikes: "with_comments_and_likes",
    Top: "top",
    None: "none",
} as const;
export type PostSocialShare = (typeof PostSocialShare)[keyof typeof PostSocialShare];
