// This file was auto-generated by Fern from our API Definition.

import type * as Beehiiv from "../../../index.js";

export interface QuoteBlock extends Beehiiv.BaseBlock {
    /** The type of quote block. Defaults to "block". */
    variant?: Beehiiv.QuoteVariant;
    /** The text of the quote. */
    quote: string;
    /** The text alignment of the quote. Defaults depend on the variant. */
    alignment?: Beehiiv.TextAlignment;
    /** The author of the quote. */
    author?: string;
}
