// This file was auto-generated by Fern from our API Definition.

import type * as Beehiiv from "../../../index.js";

export interface VisibilitySettings {
    /** Whether to show the block on the web. */
    show_on_web?: boolean;
    /** Whether to show the block on the email. */
    show_on_email?: boolean;
    /** Whether to show the block to anonymous users on the web. */
    show_to_anonymous_users_web?: boolean;
    /** Whether to show the block to free subscribers. */
    show_to_free_subscribers?: boolean;
    /** Whether to show the block to paid subscribers. */
    show_to_paid_subscribers?: boolean;
    /** The exact referral count required to show the block to subscribers. */
    show_to_subscribers_with_referral_value?: number;
    /** The condition required to show the block to subscribers. */
    show_to_subscribers_with_referral_condition?: Beehiiv.ReferralCondition;
}
