/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Beehiiv from "../../../../api/index";
import * as core from "../../../../core";
import { Tier } from "../../../types/Tier";

export const GetPublicationsPublicationIdTiersTierIdResponse: core.serialization.ObjectSchema<
    serializers.GetPublicationsPublicationIdTiersTierIdResponse.Raw,
    Beehiiv.GetPublicationsPublicationIdTiersTierIdResponse
> = core.serialization.object({
    data: Tier.optional(),
});

export declare namespace GetPublicationsPublicationIdTiersTierIdResponse {
    interface Raw {
        data?: Tier.Raw | null;
    }
}
