/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Beehiiv from "../../../../api/index";
import * as core from "../../../../core";

export const PatchPublicationsPublicationIdTiersTierIdRequestPricesAttributesItemCurrency: core.serialization.Schema<
    serializers.PatchPublicationsPublicationIdTiersTierIdRequestPricesAttributesItemCurrency.Raw,
    Beehiiv.PatchPublicationsPublicationIdTiersTierIdRequestPricesAttributesItemCurrency
> = core.serialization.enum_(["usd", "aud", "cad", "eur", "inr", "brl"]);

export declare namespace PatchPublicationsPublicationIdTiersTierIdRequestPricesAttributesItemCurrency {
    type Raw = "usd" | "aud" | "cad" | "eur" | "inr" | "brl";
}
