/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Beehiiv from "../../../../api/index";
import * as core from "../../../../core";

export const PostPublicationsPublicationIdTiersRequestPricesAttributesItemInterval: core.serialization.Schema<
    serializers.PostPublicationsPublicationIdTiersRequestPricesAttributesItemInterval.Raw,
    Beehiiv.PostPublicationsPublicationIdTiersRequestPricesAttributesItemInterval
> = core.serialization.enum_(["month", "year"]);

export declare namespace PostPublicationsPublicationIdTiersRequestPricesAttributesItemInterval {
    type Raw = "month" | "year";
}
