/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { mockServerPool } from "../mock-server/MockServerPool";
import { BeehiivClient } from "../../src/Client";

describe("BulkSubscriptions", () => {
    test("create", async () => {
        const server = mockServerPool.createServer();
        const client = new BeehiivClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            subscriptions: [
                {
                    email: "bruce.wayne@wayneenterprise.com",
                    reactivate_existing: false,
                    send_welcome_email: false,
                    custom_fields: [{ name: "Favorite Color", value: "Red" }],
                },
                {
                    email: "lucius.fox@wayneenterprise.com",
                    reactivate_existing: false,
                    send_welcome_email: false,
                    custom_fields: [{ name: "Favorite Color", value: "Blue" }],
                },
            ],
        };
        const rawResponseBody = {
            message: "Bulk Subscription Create Request Sent.",
            import_id: "00000000-0000-0000-0000-000000000000",
        };
        server
            .mockEndpoint()
            .post("/publications/pub_00000000-0000-0000-0000-000000000000/bulk_subscriptions")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.bulkSubscriptions.create("pub_00000000-0000-0000-0000-000000000000", {
            subscriptions: [
                {
                    email: "bruce.wayne@wayneenterprise.com",
                    reactivate_existing: false,
                    send_welcome_email: false,
                    custom_fields: [
                        {
                            name: "Favorite Color",
                            value: "Red",
                        },
                    ],
                },
                {
                    email: "lucius.fox@wayneenterprise.com",
                    reactivate_existing: false,
                    send_welcome_email: false,
                    custom_fields: [
                        {
                            name: "Favorite Color",
                            value: "Blue",
                        },
                    ],
                },
            ],
        });
        expect(response).toEqual({
            message: "Bulk Subscription Create Request Sent.",
            import_id: "00000000-0000-0000-0000-000000000000",
        });
    });
});
