// This file was auto-generated by Fern from our API Definition.

import * as Beehiiv from "../../src/api/index";
import { BeehiivClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("CustomFieldsClient", () => {
    test("create (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new BeehiivClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { kind: "string", display: "Display" };
        const rawResponseBody = {
            data: {
                id: "00000000-0000-0000-0000-000000000000",
                kind: "string",
                display: "Display",
                created: 1672531200,
            },
        };
        server
            .mockEndpoint()
            .post("/publications/publicationId/custom_fields")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.customFields.create("publicationId", {
            kind: "string",
            display: "Display",
        });
        expect(response).toEqual({
            data: {
                id: "00000000-0000-0000-0000-000000000000",
                kind: "string",
                display: "Display",
                created: 1672531200,
            },
        });
    });

    test("create (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new BeehiivClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { kind: "string", display: "display" };
        const rawResponseBody = {
            status: 1,
            statusText: "statusText",
            errors: [
                { message: "message", code: "code" },
                { message: "message", code: "code" },
            ],
        };
        server
            .mockEndpoint()
            .post("/publications/publicationId/custom_fields")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customFields.create("publicationId", {
                kind: "string",
                display: "display",
            });
        }).rejects.toThrow(Beehiiv.BadRequestError);
    });

    test("create (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new BeehiivClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { kind: "string", display: "display" };
        const rawResponseBody = {
            status: 1,
            statusText: "statusText",
            errors: [
                { message: "message", code: "code" },
                { message: "message", code: "code" },
            ],
        };
        server
            .mockEndpoint()
            .post("/publications/publicationId/custom_fields")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customFields.create("publicationId", {
                kind: "string",
                display: "display",
            });
        }).rejects.toThrow(Beehiiv.NotFoundError);
    });

    test("create (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new BeehiivClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { kind: "string", display: "display" };
        const rawResponseBody = {
            status: 1,
            statusText: "statusText",
            errors: [
                { message: "message", code: "code" },
                { message: "message", code: "code" },
            ],
        };
        server
            .mockEndpoint()
            .post("/publications/publicationId/custom_fields")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customFields.create("publicationId", {
                kind: "string",
                display: "display",
            });
        }).rejects.toThrow(Beehiiv.TooManyRequestsError);
    });

    test("create (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new BeehiivClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { kind: "string", display: "display" };
        const rawResponseBody = {
            status: 1,
            statusText: "statusText",
            errors: [
                { message: "message", code: "code" },
                { message: "message", code: "code" },
            ],
        };
        server
            .mockEndpoint()
            .post("/publications/publicationId/custom_fields")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customFields.create("publicationId", {
                kind: "string",
                display: "display",
            });
        }).rejects.toThrow(Beehiiv.InternalServerError);
    });

    test("show (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new BeehiivClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            data: {
                id: "00000000-0000-0000-0000-000000000000",
                kind: "string",
                display: "Display",
                created: 1672531200,
            },
        };
        server
            .mockEndpoint()
            .get("/publications/publicationId/custom_fields/id")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.customFields.show("publicationId", "id");
        expect(response).toEqual({
            data: {
                id: "00000000-0000-0000-0000-000000000000",
                kind: "string",
                display: "Display",
                created: 1672531200,
            },
        });
    });

    test("show (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new BeehiivClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            status: 1,
            statusText: "statusText",
            errors: [
                { message: "message", code: "code" },
                { message: "message", code: "code" },
            ],
        };
        server
            .mockEndpoint()
            .get("/publications/publicationId/custom_fields/id")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customFields.show("publicationId", "id");
        }).rejects.toThrow(Beehiiv.BadRequestError);
    });

    test("show (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new BeehiivClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            status: 1,
            statusText: "statusText",
            errors: [
                { message: "message", code: "code" },
                { message: "message", code: "code" },
            ],
        };
        server
            .mockEndpoint()
            .get("/publications/publicationId/custom_fields/id")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customFields.show("publicationId", "id");
        }).rejects.toThrow(Beehiiv.NotFoundError);
    });

    test("show (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new BeehiivClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            status: 1,
            statusText: "statusText",
            errors: [
                { message: "message", code: "code" },
                { message: "message", code: "code" },
            ],
        };
        server
            .mockEndpoint()
            .get("/publications/publicationId/custom_fields/id")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customFields.show("publicationId", "id");
        }).rejects.toThrow(Beehiiv.TooManyRequestsError);
    });

    test("show (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new BeehiivClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            status: 1,
            statusText: "statusText",
            errors: [
                { message: "message", code: "code" },
                { message: "message", code: "code" },
            ],
        };
        server
            .mockEndpoint()
            .get("/publications/publicationId/custom_fields/id")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customFields.show("publicationId", "id");
        }).rejects.toThrow(Beehiiv.InternalServerError);
    });

    test("index (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new BeehiivClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            data: [
                { id: "00000000-0000-0000-0000-000000000000", kind: "string", display: "Display", created: 1672531200 },
                {
                    id: "00000000-0000-0000-0000-000000000000",
                    kind: "list",
                    display: "Dropdown Field",
                    created: 1672531200,
                    options: ["Option 1", "Option 2", "Option 3"],
                },
            ],
            limit: 10,
            page: 1,
            total_results: 20,
            total_pages: 2,
        };
        server
            .mockEndpoint()
            .get("/publications/publicationId/custom_fields")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.customFields.index("publicationId");
        expect(response).toEqual({
            data: [
                {
                    id: "00000000-0000-0000-0000-000000000000",
                    kind: "string",
                    display: "Display",
                    created: 1672531200,
                },
                {
                    id: "00000000-0000-0000-0000-000000000000",
                    kind: "list",
                    display: "Dropdown Field",
                    created: 1672531200,
                    options: ["Option 1", "Option 2", "Option 3"],
                },
            ],
            limit: 10,
            page: 1,
            total_results: 20,
            total_pages: 2,
        });
    });

    test("index (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new BeehiivClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            status: 1,
            statusText: "statusText",
            errors: [
                { message: "message", code: "code" },
                { message: "message", code: "code" },
            ],
        };
        server
            .mockEndpoint()
            .get("/publications/publicationId/custom_fields")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customFields.index("publicationId");
        }).rejects.toThrow(Beehiiv.BadRequestError);
    });

    test("index (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new BeehiivClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            status: 1,
            statusText: "statusText",
            errors: [
                { message: "message", code: "code" },
                { message: "message", code: "code" },
            ],
        };
        server
            .mockEndpoint()
            .get("/publications/publicationId/custom_fields")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customFields.index("publicationId");
        }).rejects.toThrow(Beehiiv.NotFoundError);
    });

    test("index (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new BeehiivClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            status: 1,
            statusText: "statusText",
            errors: [
                { message: "message", code: "code" },
                { message: "message", code: "code" },
            ],
        };
        server
            .mockEndpoint()
            .get("/publications/publicationId/custom_fields")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customFields.index("publicationId");
        }).rejects.toThrow(Beehiiv.TooManyRequestsError);
    });

    test("index (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new BeehiivClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            status: 1,
            statusText: "statusText",
            errors: [
                { message: "message", code: "code" },
                { message: "message", code: "code" },
            ],
        };
        server
            .mockEndpoint()
            .get("/publications/publicationId/custom_fields")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customFields.index("publicationId");
        }).rejects.toThrow(Beehiiv.InternalServerError);
    });

    test("put (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new BeehiivClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { display: "New Display" };
        const rawResponseBody = { data: { id: "id", display: "display", kind: "string", created: 1672531200 } };
        server
            .mockEndpoint()
            .put("/publications/publicationId/custom_fields/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.customFields.put("publicationId", "id", {
            display: "New Display",
        });
        expect(response).toEqual({
            data: {
                id: "id",
                display: "display",
                kind: "string",
                created: 1672531200,
            },
        });
    });

    test("put (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new BeehiivClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            status: 1,
            statusText: "statusText",
            errors: [
                { message: "message", code: "code" },
                { message: "message", code: "code" },
            ],
        };
        server
            .mockEndpoint()
            .put("/publications/publicationId/custom_fields/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customFields.put("publicationId", "id");
        }).rejects.toThrow(Beehiiv.BadRequestError);
    });

    test("put (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new BeehiivClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            status: 1,
            statusText: "statusText",
            errors: [
                { message: "message", code: "code" },
                { message: "message", code: "code" },
            ],
        };
        server
            .mockEndpoint()
            .put("/publications/publicationId/custom_fields/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customFields.put("publicationId", "id");
        }).rejects.toThrow(Beehiiv.NotFoundError);
    });

    test("put (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new BeehiivClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            status: 1,
            statusText: "statusText",
            errors: [
                { message: "message", code: "code" },
                { message: "message", code: "code" },
            ],
        };
        server
            .mockEndpoint()
            .put("/publications/publicationId/custom_fields/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customFields.put("publicationId", "id");
        }).rejects.toThrow(Beehiiv.TooManyRequestsError);
    });

    test("put (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new BeehiivClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            status: 1,
            statusText: "statusText",
            errors: [
                { message: "message", code: "code" },
                { message: "message", code: "code" },
            ],
        };
        server
            .mockEndpoint()
            .put("/publications/publicationId/custom_fields/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customFields.put("publicationId", "id");
        }).rejects.toThrow(Beehiiv.InternalServerError);
    });

    test("patch (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new BeehiivClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { display: "New Display" };
        const rawResponseBody = { data: { id: "id", display: "display", kind: "string", created: 1672531200 } };
        server
            .mockEndpoint()
            .patch("/publications/publicationId/custom_fields/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.customFields.patch("publicationId", "id", {
            display: "New Display",
        });
        expect(response).toEqual({
            data: {
                id: "id",
                display: "display",
                kind: "string",
                created: 1672531200,
            },
        });
    });

    test("patch (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new BeehiivClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            status: 1,
            statusText: "statusText",
            errors: [
                { message: "message", code: "code" },
                { message: "message", code: "code" },
            ],
        };
        server
            .mockEndpoint()
            .patch("/publications/publicationId/custom_fields/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customFields.patch("publicationId", "id");
        }).rejects.toThrow(Beehiiv.BadRequestError);
    });

    test("patch (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new BeehiivClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            status: 1,
            statusText: "statusText",
            errors: [
                { message: "message", code: "code" },
                { message: "message", code: "code" },
            ],
        };
        server
            .mockEndpoint()
            .patch("/publications/publicationId/custom_fields/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customFields.patch("publicationId", "id");
        }).rejects.toThrow(Beehiiv.NotFoundError);
    });

    test("patch (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new BeehiivClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            status: 1,
            statusText: "statusText",
            errors: [
                { message: "message", code: "code" },
                { message: "message", code: "code" },
            ],
        };
        server
            .mockEndpoint()
            .patch("/publications/publicationId/custom_fields/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customFields.patch("publicationId", "id");
        }).rejects.toThrow(Beehiiv.TooManyRequestsError);
    });

    test("patch (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new BeehiivClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            status: 1,
            statusText: "statusText",
            errors: [
                { message: "message", code: "code" },
                { message: "message", code: "code" },
            ],
        };
        server
            .mockEndpoint()
            .patch("/publications/publicationId/custom_fields/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customFields.patch("publicationId", "id");
        }).rejects.toThrow(Beehiiv.InternalServerError);
    });

    test("delete (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new BeehiivClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};
        server
            .mockEndpoint()
            .delete("/publications/publicationId/custom_fields/id")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.customFields.delete("publicationId", "id");
        expect(response).toEqual({});
    });

    test("delete (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new BeehiivClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            status: 1,
            statusText: "statusText",
            errors: [
                { message: "message", code: "code" },
                { message: "message", code: "code" },
            ],
        };
        server
            .mockEndpoint()
            .delete("/publications/publicationId/custom_fields/id")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customFields.delete("publicationId", "id");
        }).rejects.toThrow(Beehiiv.BadRequestError);
    });

    test("delete (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new BeehiivClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            status: 1,
            statusText: "statusText",
            errors: [
                { message: "message", code: "code" },
                { message: "message", code: "code" },
            ],
        };
        server
            .mockEndpoint()
            .delete("/publications/publicationId/custom_fields/id")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customFields.delete("publicationId", "id");
        }).rejects.toThrow(Beehiiv.NotFoundError);
    });

    test("delete (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new BeehiivClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            status: 1,
            statusText: "statusText",
            errors: [
                { message: "message", code: "code" },
                { message: "message", code: "code" },
            ],
        };
        server
            .mockEndpoint()
            .delete("/publications/publicationId/custom_fields/id")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customFields.delete("publicationId", "id");
        }).rejects.toThrow(Beehiiv.TooManyRequestsError);
    });

    test("delete (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new BeehiivClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            status: 1,
            statusText: "statusText",
            errors: [
                { message: "message", code: "code" },
                { message: "message", code: "code" },
            ],
        };
        server
            .mockEndpoint()
            .delete("/publications/publicationId/custom_fields/id")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customFields.delete("publicationId", "id");
        }).rejects.toThrow(Beehiiv.InternalServerError);
    });
});
