// This file was auto-generated by Fern from our API Definition.

import * as Beehiiv from "../../src/api/index";
import { BeehiivClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("PostTemplatesClient", () => {
    test("index (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new BeehiivClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            data: [
                { id: "post_template_00000000-0000-0000-0000-000000000000", name: "Newsletter Template" },
                { id: "post_template_11111111-1111-1111-1111-111111111111", name: "Blog Post Template" },
            ],
            limit: 10,
            page: 1,
            total_results: 2,
            total_pages: 1,
        };
        server
            .mockEndpoint()
            .get("/publications/pub_00000000-0000-0000-0000-000000000000/post_templates")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.postTemplates.index("pub_00000000-0000-0000-0000-000000000000");
        expect(response).toEqual({
            data: [
                {
                    id: "post_template_00000000-0000-0000-0000-000000000000",
                    name: "Newsletter Template",
                },
                {
                    id: "post_template_11111111-1111-1111-1111-111111111111",
                    name: "Blog Post Template",
                },
            ],
            limit: 10,
            page: 1,
            total_results: 2,
            total_pages: 1,
        });
    });

    test("index (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new BeehiivClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            status: 1,
            statusText: "statusText",
            errors: [
                { message: "message", code: "code" },
                { message: "message", code: "code" },
            ],
        };
        server
            .mockEndpoint()
            .get("/publications/publicationId/post_templates")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.postTemplates.index("publicationId");
        }).rejects.toThrow(Beehiiv.BadRequestError);
    });

    test("index (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new BeehiivClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            status: 1,
            statusText: "statusText",
            errors: [
                { message: "message", code: "code" },
                { message: "message", code: "code" },
            ],
        };
        server
            .mockEndpoint()
            .get("/publications/publicationId/post_templates")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.postTemplates.index("publicationId");
        }).rejects.toThrow(Beehiiv.UnauthorizedError);
    });

    test("index (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new BeehiivClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            status: 1,
            statusText: "statusText",
            errors: [
                { message: "message", code: "code" },
                { message: "message", code: "code" },
            ],
        };
        server
            .mockEndpoint()
            .get("/publications/publicationId/post_templates")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.postTemplates.index("publicationId");
        }).rejects.toThrow(Beehiiv.ForbiddenError);
    });

    test("index (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new BeehiivClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            status: 1,
            statusText: "statusText",
            errors: [
                { message: "message", code: "code" },
                { message: "message", code: "code" },
            ],
        };
        server
            .mockEndpoint()
            .get("/publications/publicationId/post_templates")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.postTemplates.index("publicationId");
        }).rejects.toThrow(Beehiiv.NotFoundError);
    });

    test("index (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new BeehiivClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            status: 1,
            statusText: "statusText",
            errors: [
                { message: "message", code: "code" },
                { message: "message", code: "code" },
            ],
        };
        server
            .mockEndpoint()
            .get("/publications/publicationId/post_templates")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.postTemplates.index("publicationId");
        }).rejects.toThrow(Beehiiv.TooManyRequestsError);
    });

    test("index (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new BeehiivClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            status: 1,
            statusText: "statusText",
            errors: [
                { message: "message", code: "code" },
                { message: "message", code: "code" },
            ],
        };
        server
            .mockEndpoint()
            .get("/publications/publicationId/post_templates")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.postTemplates.index("publicationId");
        }).rejects.toThrow(Beehiiv.InternalServerError);
    });
});
