// This file was auto-generated by Fern from our API Definition.

import * as Beehiiv from "../../src/api/index";
import { BeehiivClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("SubscriptionsClient", () => {
    test("create (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new BeehiivClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            email: "bruce.wayne@wayneenterprise.com",
            reactivate_existing: false,
            send_welcome_email: false,
            utm_source: "WayneEnterprise",
            utm_medium: "organic",
            utm_campaign: "fall_2022_promotion",
            referring_site: "www.wayneenterprise.com/blog",
            custom_fields: [
                { name: "First Name", value: "Bruce" },
                { name: "Last Name", value: "Wayne" },
            ],
            stripe_customer_id: "cus_12345abcde",
        };
        const rawResponseBody = {
            data: {
                id: "sub_00000000-0000-0000-0000-000000000000",
                email: "example@example.com",
                status: "validating",
                created: 1666800076,
                subscription_tier: "free",
                subscription_premium_tier_names: ["Premium", "Gold"],
                utm_source: "Twitter",
                utm_medium: "organic",
                utm_channel: "website",
                utm_campaign: "utm_campaign",
                referring_site: "https://www.blog.com",
                referral_code: "referral_code",
            },
        };
        server
            .mockEndpoint()
            .post("/publications/pub_00000000-0000-0000-0000-000000000000/subscriptions")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.subscriptions.create("pub_00000000-0000-0000-0000-000000000000", {
            email: "bruce.wayne@wayneenterprise.com",
            reactivate_existing: false,
            send_welcome_email: false,
            utm_source: "WayneEnterprise",
            utm_medium: "organic",
            utm_campaign: "fall_2022_promotion",
            referring_site: "www.wayneenterprise.com/blog",
            custom_fields: [
                {
                    name: "First Name",
                    value: "Bruce",
                },
                {
                    name: "Last Name",
                    value: "Wayne",
                },
            ],
            stripe_customer_id: "cus_12345abcde",
        });
        expect(response).toEqual({
            data: {
                id: "sub_00000000-0000-0000-0000-000000000000",
                email: "example@example.com",
                status: "validating",
                created: 1666800076,
                subscription_tier: "free",
                subscription_premium_tier_names: ["Premium", "Gold"],
                utm_source: "Twitter",
                utm_medium: "organic",
                utm_channel: "website",
                utm_campaign: "utm_campaign",
                referring_site: "https://www.blog.com",
                referral_code: "referral_code",
            },
        });
    });

    test("create (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new BeehiivClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { email: "email" };
        const rawResponseBody = {
            status: 1,
            statusText: "statusText",
            errors: [
                { message: "message", code: "code" },
                { message: "message", code: "code" },
            ],
        };
        server
            .mockEndpoint()
            .post("/publications/publicationId/subscriptions")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.subscriptions.create("publicationId", {
                email: "email",
            });
        }).rejects.toThrow(Beehiiv.BadRequestError);
    });

    test("create (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new BeehiivClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { email: "email" };
        const rawResponseBody = {
            status: 1,
            statusText: "statusText",
            errors: [
                { message: "message", code: "code" },
                { message: "message", code: "code" },
            ],
        };
        server
            .mockEndpoint()
            .post("/publications/publicationId/subscriptions")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.subscriptions.create("publicationId", {
                email: "email",
            });
        }).rejects.toThrow(Beehiiv.NotFoundError);
    });

    test("create (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new BeehiivClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { email: "email" };
        const rawResponseBody = {
            status: 1,
            statusText: "statusText",
            errors: [
                { message: "message", code: "code" },
                { message: "message", code: "code" },
            ],
        };
        server
            .mockEndpoint()
            .post("/publications/publicationId/subscriptions")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.subscriptions.create("publicationId", {
                email: "email",
            });
        }).rejects.toThrow(Beehiiv.TooManyRequestsError);
    });

    test("create (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new BeehiivClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { email: "email" };
        const rawResponseBody = {
            status: 1,
            statusText: "statusText",
            errors: [
                { message: "message", code: "code" },
                { message: "message", code: "code" },
            ],
        };
        server
            .mockEndpoint()
            .post("/publications/publicationId/subscriptions")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.subscriptions.create("publicationId", {
                email: "email",
            });
        }).rejects.toThrow(Beehiiv.InternalServerError);
    });

    test("index (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new BeehiivClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            data: [
                {
                    id: "sub_00000000-0000-0000-0000-000000000000",
                    email: "example@example.com",
                    status: "validating",
                    created: 1666800076,
                    subscription_tier: "free",
                    subscription_premium_tier_names: ["Premium", "Gold"],
                    utm_source: "Twitter",
                    utm_medium: "organic",
                    utm_channel: "website",
                    utm_campaign: "utm_campaign",
                    referring_site: "https://www.blog.com",
                    referral_code: "referral_code",
                    subscription_premium_tiers: [
                        { id: "tier_00000000-0000-0000-0000-000000000000", name: "name", status: "active" },
                    ],
                    custom_fields: [{}],
                    tags: ["Premium", "Basic", "Active", "Engaged"],
                    stats: { emails_received: 25, open_rate: 60.1, click_through_rate: 25 },
                },
            ],
            limit: 10,
            has_more: true,
            next_cursor: "eyJ0aW1lc3RhbXAiOiIyMDI0LTA3LTAyVDE3OjMwOjAwLjAwMDAwMFoifQ==",
        };
        server
            .mockEndpoint()
            .get("/publications/pub_00000000-0000-0000-0000-000000000000/subscriptions")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.subscriptions.index("pub_00000000-0000-0000-0000-000000000000", {
            limit: 10,
        });
        expect(response).toEqual({
            data: [
                {
                    id: "sub_00000000-0000-0000-0000-000000000000",
                    email: "example@example.com",
                    status: "validating",
                    created: 1666800076,
                    subscription_tier: "free",
                    subscription_premium_tier_names: ["Premium", "Gold"],
                    utm_source: "Twitter",
                    utm_medium: "organic",
                    utm_channel: "website",
                    utm_campaign: "utm_campaign",
                    referring_site: "https://www.blog.com",
                    referral_code: "referral_code",
                    subscription_premium_tiers: [
                        {
                            id: "tier_00000000-0000-0000-0000-000000000000",
                            name: "name",
                            status: "active",
                        },
                    ],
                    custom_fields: [{}],
                    tags: ["Premium", "Basic", "Active", "Engaged"],
                    stats: {
                        emails_received: 25,
                        open_rate: 60.1,
                        click_through_rate: 25,
                    },
                },
            ],
            limit: 10,
            has_more: true,
            next_cursor: "eyJ0aW1lc3RhbXAiOiIyMDI0LTA3LTAyVDE3OjMwOjAwLjAwMDAwMFoifQ==",
        });
    });

    test("index (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new BeehiivClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            data: [
                {
                    id: "sub_11111111-1111-1111-1111-111111111111",
                    email: "next@example.com",
                    status: "active",
                    created: 1666800000,
                    subscription_tier: "premium",
                    subscription_premium_tier_names: ["Premium"],
                    utm_source: "Direct",
                    utm_medium: "email",
                    utm_channel: "website",
                    utm_campaign: "welcome_series",
                    referring_site: "https://www.example.com",
                    referral_code: "WELCOME2024",
                    subscription_premium_tiers: [
                        { id: "tier_11111111-1111-1111-1111-111111111111", name: "Premium", status: "active" },
                    ],
                    custom_fields: [{}],
                    tags: ["Premium", "New"],
                    stats: { emails_received: 15, open_rate: 45.2, click_through_rate: 18.5 },
                },
            ],
            limit: 10,
            has_more: false,
        };
        server
            .mockEndpoint()
            .get("/publications/pub_00000000-0000-0000-0000-000000000000/subscriptions")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.subscriptions.index("pub_00000000-0000-0000-0000-000000000000", {
            limit: 10,
            cursor: "eyJ0aW1lc3RhbXAiOiIyMDI0LTA3LTAyVDE3OjMwOjAwLjAwMDAwMFoifQ==",
        });
        expect(response).toEqual({
            data: [
                {
                    id: "sub_11111111-1111-1111-1111-111111111111",
                    email: "next@example.com",
                    status: "active",
                    created: 1666800000,
                    subscription_tier: "premium",
                    subscription_premium_tier_names: ["Premium"],
                    utm_source: "Direct",
                    utm_medium: "email",
                    utm_channel: "website",
                    utm_campaign: "welcome_series",
                    referring_site: "https://www.example.com",
                    referral_code: "WELCOME2024",
                    subscription_premium_tiers: [
                        {
                            id: "tier_11111111-1111-1111-1111-111111111111",
                            name: "Premium",
                            status: "active",
                        },
                    ],
                    custom_fields: [{}],
                    tags: ["Premium", "New"],
                    stats: {
                        emails_received: 15,
                        open_rate: 45.2,
                        click_through_rate: 18.5,
                    },
                },
            ],
            limit: 10,
            has_more: false,
        });
    });

    test("index (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new BeehiivClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            data: [
                {
                    id: "sub_00000000-0000-0000-0000-000000000000",
                    email: "example@example.com",
                    status: "validating",
                    created: 1666800076,
                    subscription_tier: "free",
                    subscription_premium_tier_names: ["Premium", "Gold"],
                    utm_source: "Twitter",
                    utm_medium: "organic",
                    utm_channel: "website",
                    utm_campaign: "utm_campaign",
                    referring_site: "https://www.blog.com",
                    referral_code: "referral_code",
                    subscription_premium_tiers: [
                        { id: "tier_00000000-0000-0000-0000-000000000000", name: "name", status: "active" },
                    ],
                    custom_fields: [{}],
                    tags: ["Premium", "Basic", "Active", "Engaged"],
                    stats: { emails_received: 25, open_rate: 60.1, click_through_rate: 25 },
                },
            ],
            limit: 10,
            page: 1,
            total_results: 1500,
            total_pages: 150,
        };
        server
            .mockEndpoint()
            .get("/publications/pub_00000000-0000-0000-0000-000000000000/subscriptions")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.subscriptions.index("pub_00000000-0000-0000-0000-000000000000", {
            email: "clark@dailyplanet.com",
            page: 1,
            limit: 10,
        });
        expect(response).toEqual({
            data: [
                {
                    id: "sub_00000000-0000-0000-0000-000000000000",
                    email: "example@example.com",
                    status: "validating",
                    created: 1666800076,
                    subscription_tier: "free",
                    subscription_premium_tier_names: ["Premium", "Gold"],
                    utm_source: "Twitter",
                    utm_medium: "organic",
                    utm_channel: "website",
                    utm_campaign: "utm_campaign",
                    referring_site: "https://www.blog.com",
                    referral_code: "referral_code",
                    subscription_premium_tiers: [
                        {
                            id: "tier_00000000-0000-0000-0000-000000000000",
                            name: "name",
                            status: "active",
                        },
                    ],
                    custom_fields: [{}],
                    tags: ["Premium", "Basic", "Active", "Engaged"],
                    stats: {
                        emails_received: 25,
                        open_rate: 60.1,
                        click_through_rate: 25,
                    },
                },
            ],
            limit: 10,
            page: 1,
            total_results: 1500,
            total_pages: 150,
        });
    });

    test("index (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new BeehiivClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            status: 1,
            statusText: "statusText",
            errors: [
                { message: "message", code: "code" },
                { message: "message", code: "code" },
            ],
        };
        server
            .mockEndpoint()
            .get("/publications/publicationId/subscriptions")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.subscriptions.index("publicationId");
        }).rejects.toThrow(Beehiiv.BadRequestError);
    });

    test("index (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new BeehiivClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            status: 1,
            statusText: "statusText",
            errors: [
                { message: "message", code: "code" },
                { message: "message", code: "code" },
            ],
        };
        server
            .mockEndpoint()
            .get("/publications/publicationId/subscriptions")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.subscriptions.index("publicationId");
        }).rejects.toThrow(Beehiiv.NotFoundError);
    });

    test("index (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new BeehiivClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            status: 1,
            statusText: "statusText",
            errors: [
                { message: "message", code: "code" },
                { message: "message", code: "code" },
            ],
        };
        server
            .mockEndpoint()
            .get("/publications/publicationId/subscriptions")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.subscriptions.index("publicationId");
        }).rejects.toThrow(Beehiiv.TooManyRequestsError);
    });

    test("index (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new BeehiivClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            status: 1,
            statusText: "statusText",
            errors: [
                { message: "message", code: "code" },
                { message: "message", code: "code" },
            ],
        };
        server
            .mockEndpoint()
            .get("/publications/publicationId/subscriptions")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.subscriptions.index("publicationId");
        }).rejects.toThrow(Beehiiv.InternalServerError);
    });

    test("get-by-email (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new BeehiivClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            data: {
                id: "sub_00000000-0000-0000-0000-000000000000",
                email: "example@example.com",
                status: "validating",
                created: 1666800076,
                subscription_tier: "free",
                subscription_premium_tier_names: ["Premium", "Gold"],
                utm_source: "Twitter",
                utm_medium: "organic",
                utm_channel: "website",
                utm_campaign: "utm_campaign",
                referring_site: "https://www.blog.com",
                referral_code: "referral_code",
                subscription_premium_tiers: [
                    { id: "tier_00000000-0000-0000-0000-000000000000", name: "name", status: "active" },
                ],
                custom_fields: [{}],
                tags: ["Premium", "Basic", "Active", "Engaged"],
                stats: { emails_received: 25, open_rate: 60.1, click_through_rate: 25 },
            },
        };
        server
            .mockEndpoint()
            .get("/publications/pub_00000000-0000-0000-0000-000000000000/subscriptions/by_email/work%40example.com")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.subscriptions.getByEmail(
            "pub_00000000-0000-0000-0000-000000000000",
            "work@example.com",
        );
        expect(response).toEqual({
            data: {
                id: "sub_00000000-0000-0000-0000-000000000000",
                email: "example@example.com",
                status: "validating",
                created: 1666800076,
                subscription_tier: "free",
                subscription_premium_tier_names: ["Premium", "Gold"],
                utm_source: "Twitter",
                utm_medium: "organic",
                utm_channel: "website",
                utm_campaign: "utm_campaign",
                referring_site: "https://www.blog.com",
                referral_code: "referral_code",
                subscription_premium_tiers: [
                    {
                        id: "tier_00000000-0000-0000-0000-000000000000",
                        name: "name",
                        status: "active",
                    },
                ],
                custom_fields: [{}],
                tags: ["Premium", "Basic", "Active", "Engaged"],
                stats: {
                    emails_received: 25,
                    open_rate: 60.1,
                    click_through_rate: 25,
                },
            },
        });
    });

    test("get-by-email (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new BeehiivClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            status: 1,
            statusText: "statusText",
            errors: [
                { message: "message", code: "code" },
                { message: "message", code: "code" },
            ],
        };
        server
            .mockEndpoint()
            .get("/publications/publicationId/subscriptions/by_email/email")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.subscriptions.getByEmail("publicationId", "email");
        }).rejects.toThrow(Beehiiv.BadRequestError);
    });

    test("get-by-email (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new BeehiivClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            status: 1,
            statusText: "statusText",
            errors: [
                { message: "message", code: "code" },
                { message: "message", code: "code" },
            ],
        };
        server
            .mockEndpoint()
            .get("/publications/publicationId/subscriptions/by_email/email")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.subscriptions.getByEmail("publicationId", "email");
        }).rejects.toThrow(Beehiiv.NotFoundError);
    });

    test("get-by-email (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new BeehiivClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            status: 1,
            statusText: "statusText",
            errors: [
                { message: "message", code: "code" },
                { message: "message", code: "code" },
            ],
        };
        server
            .mockEndpoint()
            .get("/publications/publicationId/subscriptions/by_email/email")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.subscriptions.getByEmail("publicationId", "email");
        }).rejects.toThrow(Beehiiv.TooManyRequestsError);
    });

    test("get-by-email (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new BeehiivClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            status: 1,
            statusText: "statusText",
            errors: [
                { message: "message", code: "code" },
                { message: "message", code: "code" },
            ],
        };
        server
            .mockEndpoint()
            .get("/publications/publicationId/subscriptions/by_email/email")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.subscriptions.getByEmail("publicationId", "email");
        }).rejects.toThrow(Beehiiv.InternalServerError);
    });

    test("get-by-id (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new BeehiivClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            data: {
                id: "sub_00000000-0000-0000-0000-000000000000",
                email: "example@example.com",
                status: "validating",
                created: 1666800076,
                subscription_tier: "free",
                subscription_premium_tier_names: ["Premium", "Gold"],
                utm_source: "Twitter",
                utm_medium: "organic",
                utm_channel: "website",
                utm_campaign: "utm_campaign",
                referring_site: "https://www.blog.com",
                referral_code: "referral_code",
            },
        };
        server
            .mockEndpoint()
            .get(
                "/publications/pub_00000000-0000-0000-0000-000000000000/subscriptions/sub_00000000-0000-0000-0000-000000000000",
            )
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.subscriptions.getById(
            "pub_00000000-0000-0000-0000-000000000000",
            "sub_00000000-0000-0000-0000-000000000000",
        );
        expect(response).toEqual({
            data: {
                id: "sub_00000000-0000-0000-0000-000000000000",
                email: "example@example.com",
                status: "validating",
                created: 1666800076,
                subscription_tier: "free",
                subscription_premium_tier_names: ["Premium", "Gold"],
                utm_source: "Twitter",
                utm_medium: "organic",
                utm_channel: "website",
                utm_campaign: "utm_campaign",
                referring_site: "https://www.blog.com",
                referral_code: "referral_code",
            },
        });
    });

    test("get-by-id (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new BeehiivClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            status: 1,
            statusText: "statusText",
            errors: [
                { message: "message", code: "code" },
                { message: "message", code: "code" },
            ],
        };
        server
            .mockEndpoint()
            .get("/publications/publicationId/subscriptions/subscriptionId")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.subscriptions.getById("publicationId", "subscriptionId");
        }).rejects.toThrow(Beehiiv.BadRequestError);
    });

    test("get-by-id (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new BeehiivClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            status: 1,
            statusText: "statusText",
            errors: [
                { message: "message", code: "code" },
                { message: "message", code: "code" },
            ],
        };
        server
            .mockEndpoint()
            .get("/publications/publicationId/subscriptions/subscriptionId")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.subscriptions.getById("publicationId", "subscriptionId");
        }).rejects.toThrow(Beehiiv.NotFoundError);
    });

    test("get-by-id (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new BeehiivClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            status: 1,
            statusText: "statusText",
            errors: [
                { message: "message", code: "code" },
                { message: "message", code: "code" },
            ],
        };
        server
            .mockEndpoint()
            .get("/publications/publicationId/subscriptions/subscriptionId")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.subscriptions.getById("publicationId", "subscriptionId");
        }).rejects.toThrow(Beehiiv.TooManyRequestsError);
    });

    test("get-by-id (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new BeehiivClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            status: 1,
            statusText: "statusText",
            errors: [
                { message: "message", code: "code" },
                { message: "message", code: "code" },
            ],
        };
        server
            .mockEndpoint()
            .get("/publications/publicationId/subscriptions/subscriptionId")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.subscriptions.getById("publicationId", "subscriptionId");
        }).rejects.toThrow(Beehiiv.InternalServerError);
    });

    test("get-by-subscriber-id (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new BeehiivClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            data: {
                id: "sub_00000000-0000-0000-0000-000000000000",
                email: "example@example.com",
                status: "validating",
                created: 1666800076,
                subscription_tier: "free",
                subscription_premium_tier_names: ["Premium", "Gold"],
                utm_source: "Twitter",
                utm_medium: "organic",
                utm_channel: "website",
                utm_campaign: "utm_campaign",
                referring_site: "https://www.blog.com",
                referral_code: "referral_code",
            },
        };
        server
            .mockEndpoint()
            .get(
                "/publications/pub_00000000-0000-0000-0000-000000000000/subscriptions/by_subscriber_id/00000000-0000-0000-0000-000000000000",
            )
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.subscriptions.getBySubscriberId(
            "pub_00000000-0000-0000-0000-000000000000",
            "00000000-0000-0000-0000-000000000000",
        );
        expect(response).toEqual({
            data: {
                id: "sub_00000000-0000-0000-0000-000000000000",
                email: "example@example.com",
                status: "validating",
                created: 1666800076,
                subscription_tier: "free",
                subscription_premium_tier_names: ["Premium", "Gold"],
                utm_source: "Twitter",
                utm_medium: "organic",
                utm_channel: "website",
                utm_campaign: "utm_campaign",
                referring_site: "https://www.blog.com",
                referral_code: "referral_code",
            },
        });
    });

    test("get-by-subscriber-id (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new BeehiivClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            status: 1,
            statusText: "statusText",
            errors: [
                { message: "message", code: "code" },
                { message: "message", code: "code" },
            ],
        };
        server
            .mockEndpoint()
            .get("/publications/publicationId/subscriptions/by_subscriber_id/subscriberId")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.subscriptions.getBySubscriberId("publicationId", "subscriberId");
        }).rejects.toThrow(Beehiiv.BadRequestError);
    });

    test("get-by-subscriber-id (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new BeehiivClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            status: 1,
            statusText: "statusText",
            errors: [
                { message: "message", code: "code" },
                { message: "message", code: "code" },
            ],
        };
        server
            .mockEndpoint()
            .get("/publications/publicationId/subscriptions/by_subscriber_id/subscriberId")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.subscriptions.getBySubscriberId("publicationId", "subscriberId");
        }).rejects.toThrow(Beehiiv.NotFoundError);
    });

    test("get-by-subscriber-id (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new BeehiivClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            status: 1,
            statusText: "statusText",
            errors: [
                { message: "message", code: "code" },
                { message: "message", code: "code" },
            ],
        };
        server
            .mockEndpoint()
            .get("/publications/publicationId/subscriptions/by_subscriber_id/subscriberId")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.subscriptions.getBySubscriberId("publicationId", "subscriberId");
        }).rejects.toThrow(Beehiiv.TooManyRequestsError);
    });

    test("get-by-subscriber-id (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new BeehiivClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            status: 1,
            statusText: "statusText",
            errors: [
                { message: "message", code: "code" },
                { message: "message", code: "code" },
            ],
        };
        server
            .mockEndpoint()
            .get("/publications/publicationId/subscriptions/by_subscriber_id/subscriberId")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.subscriptions.getBySubscriberId("publicationId", "subscriberId");
        }).rejects.toThrow(Beehiiv.InternalServerError);
    });

    test("get-jwt_token (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new BeehiivClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            data: { jwt_token: "01234567890abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ" },
        };
        server
            .mockEndpoint()
            .get(
                "/publications/pub_00000000-0000-0000-0000-000000000000/subscriptions/sub_00000000-0000-0000-0000-000000000000/jwt_token",
            )
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.subscriptions.getJwtToken(
            "pub_00000000-0000-0000-0000-000000000000",
            "sub_00000000-0000-0000-0000-000000000000",
        );
        expect(response).toEqual({
            data: {
                jwt_token: "01234567890abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ",
            },
        });
    });

    test("get-jwt_token (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new BeehiivClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            status: 1,
            statusText: "statusText",
            errors: [
                { message: "message", code: "code" },
                { message: "message", code: "code" },
            ],
        };
        server
            .mockEndpoint()
            .get("/publications/publicationId/subscriptions/subscriptionId/jwt_token")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.subscriptions.getJwtToken("publicationId", "subscriptionId");
        }).rejects.toThrow(Beehiiv.BadRequestError);
    });

    test("get-jwt_token (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new BeehiivClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            status: 1,
            statusText: "statusText",
            errors: [
                { message: "message", code: "code" },
                { message: "message", code: "code" },
            ],
        };
        server
            .mockEndpoint()
            .get("/publications/publicationId/subscriptions/subscriptionId/jwt_token")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.subscriptions.getJwtToken("publicationId", "subscriptionId");
        }).rejects.toThrow(Beehiiv.NotFoundError);
    });

    test("get-jwt_token (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new BeehiivClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            status: 1,
            statusText: "statusText",
            errors: [
                { message: "message", code: "code" },
                { message: "message", code: "code" },
            ],
        };
        server
            .mockEndpoint()
            .get("/publications/publicationId/subscriptions/subscriptionId/jwt_token")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.subscriptions.getJwtToken("publicationId", "subscriptionId");
        }).rejects.toThrow(Beehiiv.TooManyRequestsError);
    });

    test("get-jwt_token (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new BeehiivClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            status: 1,
            statusText: "statusText",
            errors: [
                { message: "message", code: "code" },
                { message: "message", code: "code" },
            ],
        };
        server
            .mockEndpoint()
            .get("/publications/publicationId/subscriptions/subscriptionId/jwt_token")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.subscriptions.getJwtToken("publicationId", "subscriptionId");
        }).rejects.toThrow(Beehiiv.InternalServerError);
    });

    test("put (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new BeehiivClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            tier: "premium",
            stripe_customer_id: "cus_12345abcde",
            custom_fields: [
                { name: "First Name", value: "Bruce" },
                { name: "Last Name", value: "Wayne" },
            ],
        };
        const rawResponseBody = {
            data: {
                id: "sub_00000000-0000-0000-0000-000000000000",
                email: "example@example.com",
                status: "active",
                created: 1666800076,
                subscription_tier: "premium",
                subscription_premium_tier_names: ["Premium", "Gold"],
                utm_source: "Twitter",
                utm_medium: "organic",
                utm_channel: "website",
                utm_campaign: "utm_campaign",
                referring_site: "https://www.blog.com",
                referral_code: "referral_code",
            },
        };
        server
            .mockEndpoint()
            .put(
                "/publications/pub_00000000-0000-0000-0000-000000000000/subscriptions/sub_00000000-0000-0000-0000-000000000000",
            )
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.subscriptions.put(
            "pub_00000000-0000-0000-0000-000000000000",
            "sub_00000000-0000-0000-0000-000000000000",
            {
                tier: "premium",
                stripe_customer_id: "cus_12345abcde",
                custom_fields: [
                    {
                        name: "First Name",
                        value: "Bruce",
                    },
                    {
                        name: "Last Name",
                        value: "Wayne",
                    },
                ],
            },
        );
        expect(response).toEqual({
            data: {
                id: "sub_00000000-0000-0000-0000-000000000000",
                email: "example@example.com",
                status: "active",
                created: 1666800076,
                subscription_tier: "premium",
                subscription_premium_tier_names: ["Premium", "Gold"],
                utm_source: "Twitter",
                utm_medium: "organic",
                utm_channel: "website",
                utm_campaign: "utm_campaign",
                referring_site: "https://www.blog.com",
                referral_code: "referral_code",
            },
        });
    });

    test("put (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new BeehiivClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            status: 1,
            statusText: "statusText",
            errors: [
                { message: "message", code: "code" },
                { message: "message", code: "code" },
            ],
        };
        server
            .mockEndpoint()
            .put("/publications/publicationId/subscriptions/subscriptionId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.subscriptions.put("publicationId", "subscriptionId");
        }).rejects.toThrow(Beehiiv.BadRequestError);
    });

    test("put (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new BeehiivClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            status: 1,
            statusText: "statusText",
            errors: [
                { message: "message", code: "code" },
                { message: "message", code: "code" },
            ],
        };
        server
            .mockEndpoint()
            .put("/publications/publicationId/subscriptions/subscriptionId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.subscriptions.put("publicationId", "subscriptionId");
        }).rejects.toThrow(Beehiiv.NotFoundError);
    });

    test("put (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new BeehiivClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            status: 1,
            statusText: "statusText",
            errors: [
                { message: "message", code: "code" },
                { message: "message", code: "code" },
            ],
        };
        server
            .mockEndpoint()
            .put("/publications/publicationId/subscriptions/subscriptionId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.subscriptions.put("publicationId", "subscriptionId");
        }).rejects.toThrow(Beehiiv.TooManyRequestsError);
    });

    test("put (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new BeehiivClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            status: 1,
            statusText: "statusText",
            errors: [
                { message: "message", code: "code" },
                { message: "message", code: "code" },
            ],
        };
        server
            .mockEndpoint()
            .put("/publications/publicationId/subscriptions/subscriptionId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.subscriptions.put("publicationId", "subscriptionId");
        }).rejects.toThrow(Beehiiv.InternalServerError);
    });

    test("patch (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new BeehiivClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            tier: "premium",
            stripe_customer_id: "cus_12345abcde",
            custom_fields: [
                { name: "First Name", value: "Bruce" },
                { name: "Last Name", value: "Wayne" },
            ],
        };
        const rawResponseBody = {
            data: {
                id: "sub_00000000-0000-0000-0000-000000000000",
                email: "example@example.com",
                status: "active",
                created: 1666800076,
                subscription_tier: "premium",
                subscription_premium_tier_names: ["Premium", "Gold"],
                utm_source: "Twitter",
                utm_medium: "organic",
                utm_channel: "website",
                utm_campaign: "utm_campaign",
                referring_site: "https://www.blog.com",
                referral_code: "referral_code",
            },
        };
        server
            .mockEndpoint()
            .patch(
                "/publications/pub_00000000-0000-0000-0000-000000000000/subscriptions/sub_00000000-0000-0000-0000-000000000000",
            )
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.subscriptions.patch(
            "pub_00000000-0000-0000-0000-000000000000",
            "sub_00000000-0000-0000-0000-000000000000",
            {
                tier: "premium",
                stripe_customer_id: "cus_12345abcde",
                custom_fields: [
                    {
                        name: "First Name",
                        value: "Bruce",
                    },
                    {
                        name: "Last Name",
                        value: "Wayne",
                    },
                ],
            },
        );
        expect(response).toEqual({
            data: {
                id: "sub_00000000-0000-0000-0000-000000000000",
                email: "example@example.com",
                status: "active",
                created: 1666800076,
                subscription_tier: "premium",
                subscription_premium_tier_names: ["Premium", "Gold"],
                utm_source: "Twitter",
                utm_medium: "organic",
                utm_channel: "website",
                utm_campaign: "utm_campaign",
                referring_site: "https://www.blog.com",
                referral_code: "referral_code",
            },
        });
    });

    test("patch (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new BeehiivClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            status: 1,
            statusText: "statusText",
            errors: [
                { message: "message", code: "code" },
                { message: "message", code: "code" },
            ],
        };
        server
            .mockEndpoint()
            .patch("/publications/publicationId/subscriptions/subscriptionId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.subscriptions.patch("publicationId", "subscriptionId");
        }).rejects.toThrow(Beehiiv.BadRequestError);
    });

    test("patch (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new BeehiivClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            status: 1,
            statusText: "statusText",
            errors: [
                { message: "message", code: "code" },
                { message: "message", code: "code" },
            ],
        };
        server
            .mockEndpoint()
            .patch("/publications/publicationId/subscriptions/subscriptionId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.subscriptions.patch("publicationId", "subscriptionId");
        }).rejects.toThrow(Beehiiv.NotFoundError);
    });

    test("patch (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new BeehiivClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            status: 1,
            statusText: "statusText",
            errors: [
                { message: "message", code: "code" },
                { message: "message", code: "code" },
            ],
        };
        server
            .mockEndpoint()
            .patch("/publications/publicationId/subscriptions/subscriptionId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.subscriptions.patch("publicationId", "subscriptionId");
        }).rejects.toThrow(Beehiiv.TooManyRequestsError);
    });

    test("patch (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new BeehiivClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            status: 1,
            statusText: "statusText",
            errors: [
                { message: "message", code: "code" },
                { message: "message", code: "code" },
            ],
        };
        server
            .mockEndpoint()
            .patch("/publications/publicationId/subscriptions/subscriptionId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.subscriptions.patch("publicationId", "subscriptionId");
        }).rejects.toThrow(Beehiiv.InternalServerError);
    });

    test("update-by-email (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new BeehiivClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            tier: "premium",
            stripe_customer_id: "cus_12345abcde",
            custom_fields: [
                { name: "First Name", value: "Bruce" },
                { name: "Last Name", value: "Wayne" },
            ],
        };
        const rawResponseBody = {
            data: {
                id: "sub_00000000-0000-0000-0000-000000000000",
                email: "example@example.com",
                status: "active",
                created: 1666800076,
                subscription_tier: "premium",
                subscription_premium_tier_names: ["Premium", "Gold"],
                utm_source: "Twitter",
                utm_medium: "organic",
                utm_channel: "website",
                utm_campaign: "utm_campaign",
                referring_site: "https://www.blog.com",
                referral_code: "referral_code",
            },
        };
        server
            .mockEndpoint()
            .put("/publications/pub_00000000-0000-0000-0000-000000000000/subscriptions/by_email/example%40example.com")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.subscriptions.updateByEmail(
            "pub_00000000-0000-0000-0000-000000000000",
            "example@example.com",
            {
                tier: "premium",
                stripe_customer_id: "cus_12345abcde",
                custom_fields: [
                    {
                        name: "First Name",
                        value: "Bruce",
                    },
                    {
                        name: "Last Name",
                        value: "Wayne",
                    },
                ],
            },
        );
        expect(response).toEqual({
            data: {
                id: "sub_00000000-0000-0000-0000-000000000000",
                email: "example@example.com",
                status: "active",
                created: 1666800076,
                subscription_tier: "premium",
                subscription_premium_tier_names: ["Premium", "Gold"],
                utm_source: "Twitter",
                utm_medium: "organic",
                utm_channel: "website",
                utm_campaign: "utm_campaign",
                referring_site: "https://www.blog.com",
                referral_code: "referral_code",
            },
        });
    });

    test("update-by-email (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new BeehiivClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            status: 1,
            statusText: "statusText",
            errors: [
                { message: "message", code: "code" },
                { message: "message", code: "code" },
            ],
        };
        server
            .mockEndpoint()
            .put("/publications/publicationId/subscriptions/by_email/email")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.subscriptions.updateByEmail("publicationId", "email");
        }).rejects.toThrow(Beehiiv.BadRequestError);
    });

    test("update-by-email (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new BeehiivClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            status: 1,
            statusText: "statusText",
            errors: [
                { message: "message", code: "code" },
                { message: "message", code: "code" },
            ],
        };
        server
            .mockEndpoint()
            .put("/publications/publicationId/subscriptions/by_email/email")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.subscriptions.updateByEmail("publicationId", "email");
        }).rejects.toThrow(Beehiiv.NotFoundError);
    });

    test("update-by-email (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new BeehiivClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            status: 1,
            statusText: "statusText",
            errors: [
                { message: "message", code: "code" },
                { message: "message", code: "code" },
            ],
        };
        server
            .mockEndpoint()
            .put("/publications/publicationId/subscriptions/by_email/email")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.subscriptions.updateByEmail("publicationId", "email");
        }).rejects.toThrow(Beehiiv.TooManyRequestsError);
    });

    test("update-by-email (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new BeehiivClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            status: 1,
            statusText: "statusText",
            errors: [
                { message: "message", code: "code" },
                { message: "message", code: "code" },
            ],
        };
        server
            .mockEndpoint()
            .put("/publications/publicationId/subscriptions/by_email/email")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.subscriptions.updateByEmail("publicationId", "email");
        }).rejects.toThrow(Beehiiv.InternalServerError);
    });

    test("delete (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new BeehiivClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};
        server
            .mockEndpoint()
            .delete(
                "/publications/pub_00000000-0000-0000-0000-000000000000/subscriptions/sub_00000000-0000-0000-0000-000000000000",
            )
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.subscriptions.delete(
            "pub_00000000-0000-0000-0000-000000000000",
            "sub_00000000-0000-0000-0000-000000000000",
        );
        expect(response).toEqual({});
    });

    test("delete (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new BeehiivClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            status: 1,
            statusText: "statusText",
            errors: [
                { message: "message", code: "code" },
                { message: "message", code: "code" },
            ],
        };
        server
            .mockEndpoint()
            .delete("/publications/publicationId/subscriptions/subscriptionId")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.subscriptions.delete("publicationId", "subscriptionId");
        }).rejects.toThrow(Beehiiv.BadRequestError);
    });

    test("delete (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new BeehiivClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            status: 1,
            statusText: "statusText",
            errors: [
                { message: "message", code: "code" },
                { message: "message", code: "code" },
            ],
        };
        server
            .mockEndpoint()
            .delete("/publications/publicationId/subscriptions/subscriptionId")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.subscriptions.delete("publicationId", "subscriptionId");
        }).rejects.toThrow(Beehiiv.NotFoundError);
    });

    test("delete (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new BeehiivClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            status: 1,
            statusText: "statusText",
            errors: [
                { message: "message", code: "code" },
                { message: "message", code: "code" },
            ],
        };
        server
            .mockEndpoint()
            .delete("/publications/publicationId/subscriptions/subscriptionId")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.subscriptions.delete("publicationId", "subscriptionId");
        }).rejects.toThrow(Beehiiv.TooManyRequestsError);
    });

    test("delete (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new BeehiivClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            status: 1,
            statusText: "statusText",
            errors: [
                { message: "message", code: "code" },
                { message: "message", code: "code" },
            ],
        };
        server
            .mockEndpoint()
            .delete("/publications/publicationId/subscriptions/subscriptionId")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.subscriptions.delete("publicationId", "subscriptionId");
        }).rejects.toThrow(Beehiiv.InternalServerError);
    });
});
