// This file was auto-generated by Fern from our API Definition.

import * as Beehiiv from "../../src/api/index";
import { BeehiivClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("WebhooksClient", () => {
    test("create (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new BeehiivClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { url: "https://example.com/webhook", event_types: ["post.sent"] };
        const rawResponseBody = {
            data: {
                id: "ep_0ca1a8505a64924059c391744d0",
                url: "https://example.com/webhook",
                created: 1666800076,
                updated: 1666800076,
                event_types: ["post.sent", "subscription.confirmed"],
                description: "A webhook to receive new posts data and new subscription confirmations.",
            },
        };
        server
            .mockEndpoint()
            .post("/publications/pub_00000000-0000-0000-0000-000000000000/webhooks")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.webhooks.create("pub_00000000-0000-0000-0000-000000000000", {
            url: "https://example.com/webhook",
            event_types: ["post.sent"],
        });
        expect(response).toEqual({
            data: {
                id: "ep_0ca1a8505a64924059c391744d0",
                url: "https://example.com/webhook",
                created: 1666800076,
                updated: 1666800076,
                event_types: ["post.sent", "subscription.confirmed"],
                description: "A webhook to receive new posts data and new subscription confirmations.",
            },
        });
    });

    test("create (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new BeehiivClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { url: "url", event_types: ["post.sent", "post.sent"] };
        const rawResponseBody = {
            status: 1,
            statusText: "statusText",
            errors: [
                { message: "message", code: "code" },
                { message: "message", code: "code" },
            ],
        };
        server
            .mockEndpoint()
            .post("/publications/publicationId/webhooks")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhooks.create("publicationId", {
                url: "url",
                event_types: ["post.sent", "post.sent"],
            });
        }).rejects.toThrow(Beehiiv.BadRequestError);
    });

    test("create (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new BeehiivClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { url: "url", event_types: ["post.sent", "post.sent"] };
        const rawResponseBody = {
            status: 1,
            statusText: "statusText",
            errors: [
                { message: "message", code: "code" },
                { message: "message", code: "code" },
            ],
        };
        server
            .mockEndpoint()
            .post("/publications/publicationId/webhooks")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhooks.create("publicationId", {
                url: "url",
                event_types: ["post.sent", "post.sent"],
            });
        }).rejects.toThrow(Beehiiv.NotFoundError);
    });

    test("create (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new BeehiivClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { url: "url", event_types: ["post.sent", "post.sent"] };
        const rawResponseBody = {
            status: 1,
            statusText: "statusText",
            errors: [
                { message: "message", code: "code" },
                { message: "message", code: "code" },
            ],
        };
        server
            .mockEndpoint()
            .post("/publications/publicationId/webhooks")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhooks.create("publicationId", {
                url: "url",
                event_types: ["post.sent", "post.sent"],
            });
        }).rejects.toThrow(Beehiiv.TooManyRequestsError);
    });

    test("create (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new BeehiivClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { url: "url", event_types: ["post.sent", "post.sent"] };
        const rawResponseBody = {
            status: 1,
            statusText: "statusText",
            errors: [
                { message: "message", code: "code" },
                { message: "message", code: "code" },
            ],
        };
        server
            .mockEndpoint()
            .post("/publications/publicationId/webhooks")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhooks.create("publicationId", {
                url: "url",
                event_types: ["post.sent", "post.sent"],
            });
        }).rejects.toThrow(Beehiiv.InternalServerError);
    });

    test("index (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new BeehiivClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            data: [
                {
                    id: "ep_0ca1a8505a64924059c391744d0",
                    url: "https://example.com/webhook",
                    created: 1666800076,
                    updated: 1666800076,
                    event_types: ["post.sent", "subscription.confirmed"],
                    description: "A webhook to receive new posts data and new subscription confirmations.",
                },
            ],
        };
        server
            .mockEndpoint()
            .get("/publications/pub_00000000-0000-0000-0000-000000000000/webhooks")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.webhooks.index("pub_00000000-0000-0000-0000-000000000000");
        expect(response).toEqual({
            data: [
                {
                    id: "ep_0ca1a8505a64924059c391744d0",
                    url: "https://example.com/webhook",
                    created: 1666800076,
                    updated: 1666800076,
                    event_types: ["post.sent", "subscription.confirmed"],
                    description: "A webhook to receive new posts data and new subscription confirmations.",
                },
            ],
        });
    });

    test("index (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new BeehiivClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            status: 1,
            statusText: "statusText",
            errors: [
                { message: "message", code: "code" },
                { message: "message", code: "code" },
            ],
        };
        server
            .mockEndpoint()
            .get("/publications/publicationId/webhooks")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhooks.index("publicationId");
        }).rejects.toThrow(Beehiiv.BadRequestError);
    });

    test("index (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new BeehiivClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            status: 1,
            statusText: "statusText",
            errors: [
                { message: "message", code: "code" },
                { message: "message", code: "code" },
            ],
        };
        server
            .mockEndpoint()
            .get("/publications/publicationId/webhooks")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhooks.index("publicationId");
        }).rejects.toThrow(Beehiiv.NotFoundError);
    });

    test("index (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new BeehiivClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            status: 1,
            statusText: "statusText",
            errors: [
                { message: "message", code: "code" },
                { message: "message", code: "code" },
            ],
        };
        server
            .mockEndpoint()
            .get("/publications/publicationId/webhooks")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhooks.index("publicationId");
        }).rejects.toThrow(Beehiiv.TooManyRequestsError);
    });

    test("index (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new BeehiivClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            status: 1,
            statusText: "statusText",
            errors: [
                { message: "message", code: "code" },
                { message: "message", code: "code" },
            ],
        };
        server
            .mockEndpoint()
            .get("/publications/publicationId/webhooks")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhooks.index("publicationId");
        }).rejects.toThrow(Beehiiv.InternalServerError);
    });

    test("show (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new BeehiivClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            data: {
                id: "ep_0ca1a8505a64924059c391744d0",
                url: "https://example.com/webhook",
                created: 1666800076,
                updated: 1666800076,
                event_types: ["post.sent", "subscription.confirmed"],
                description: "A webhook to receive new posts data and new subscription confirmations.",
            },
        };
        server
            .mockEndpoint()
            .get("/publications/pub_00000000-0000-0000-0000-000000000000/webhooks/ep_0000000000000000000000000000")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.webhooks.show(
            "pub_00000000-0000-0000-0000-000000000000",
            "ep_0000000000000000000000000000",
        );
        expect(response).toEqual({
            data: {
                id: "ep_0ca1a8505a64924059c391744d0",
                url: "https://example.com/webhook",
                created: 1666800076,
                updated: 1666800076,
                event_types: ["post.sent", "subscription.confirmed"],
                description: "A webhook to receive new posts data and new subscription confirmations.",
            },
        });
    });

    test("show (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new BeehiivClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            status: 1,
            statusText: "statusText",
            errors: [
                { message: "message", code: "code" },
                { message: "message", code: "code" },
            ],
        };
        server
            .mockEndpoint()
            .get("/publications/publicationId/webhooks/endpointId")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhooks.show("publicationId", "endpointId");
        }).rejects.toThrow(Beehiiv.UnprocessableEntityError);
    });

    test("show (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new BeehiivClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            status: 1,
            statusText: "statusText",
            errors: [
                { message: "message", code: "code" },
                { message: "message", code: "code" },
            ],
        };
        server
            .mockEndpoint()
            .get("/publications/publicationId/webhooks/endpointId")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhooks.show("publicationId", "endpointId");
        }).rejects.toThrow(Beehiiv.BadRequestError);
    });

    test("show (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new BeehiivClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            status: 1,
            statusText: "statusText",
            errors: [
                { message: "message", code: "code" },
                { message: "message", code: "code" },
            ],
        };
        server
            .mockEndpoint()
            .get("/publications/publicationId/webhooks/endpointId")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhooks.show("publicationId", "endpointId");
        }).rejects.toThrow(Beehiiv.NotFoundError);
    });

    test("show (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new BeehiivClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            status: 1,
            statusText: "statusText",
            errors: [
                { message: "message", code: "code" },
                { message: "message", code: "code" },
            ],
        };
        server
            .mockEndpoint()
            .get("/publications/publicationId/webhooks/endpointId")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhooks.show("publicationId", "endpointId");
        }).rejects.toThrow(Beehiiv.TooManyRequestsError);
    });

    test("show (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new BeehiivClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            status: 1,
            statusText: "statusText",
            errors: [
                { message: "message", code: "code" },
                { message: "message", code: "code" },
            ],
        };
        server
            .mockEndpoint()
            .get("/publications/publicationId/webhooks/endpointId")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhooks.show("publicationId", "endpointId");
        }).rejects.toThrow(Beehiiv.InternalServerError);
    });

    test("update (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new BeehiivClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            event_types: ["post.sent", "subscription.confirmed"],
            description: "A webhook to receive new posts data and new subscription confirmations.",
        };
        const rawResponseBody = {
            data: {
                id: "ep_0ca1a8505a64924059c391744d0",
                url: "https://example.com/webhook",
                created: 1666800076,
                updated: 1666800076,
                event_types: ["post.sent", "subscription.confirmed"],
                description: "A webhook to receive new posts data and new subscription confirmations.",
            },
        };
        server
            .mockEndpoint()
            .patch("/publications/pub_00000000-0000-0000-0000-000000000000/webhooks/ep_0000000000000000000000000000")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.webhooks.update(
            "pub_00000000-0000-0000-0000-000000000000",
            "ep_0000000000000000000000000000",
            {
                event_types: ["post.sent", "subscription.confirmed"],
                description: "A webhook to receive new posts data and new subscription confirmations.",
            },
        );
        expect(response).toEqual({
            data: {
                id: "ep_0ca1a8505a64924059c391744d0",
                url: "https://example.com/webhook",
                created: 1666800076,
                updated: 1666800076,
                event_types: ["post.sent", "subscription.confirmed"],
                description: "A webhook to receive new posts data and new subscription confirmations.",
            },
        });
    });

    test("update (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new BeehiivClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            status: 1,
            statusText: "statusText",
            errors: [
                { message: "message", code: "code" },
                { message: "message", code: "code" },
            ],
        };
        server
            .mockEndpoint()
            .patch("/publications/publicationId/webhooks/endpointId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhooks.update("publicationId", "endpointId");
        }).rejects.toThrow(Beehiiv.BadRequestError);
    });

    test("update (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new BeehiivClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            status: 1,
            statusText: "statusText",
            errors: [
                { message: "message", code: "code" },
                { message: "message", code: "code" },
            ],
        };
        server
            .mockEndpoint()
            .patch("/publications/publicationId/webhooks/endpointId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhooks.update("publicationId", "endpointId");
        }).rejects.toThrow(Beehiiv.NotFoundError);
    });

    test("update (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new BeehiivClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            status: 1,
            statusText: "statusText",
            errors: [
                { message: "message", code: "code" },
                { message: "message", code: "code" },
            ],
        };
        server
            .mockEndpoint()
            .patch("/publications/publicationId/webhooks/endpointId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhooks.update("publicationId", "endpointId");
        }).rejects.toThrow(Beehiiv.TooManyRequestsError);
    });

    test("update (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new BeehiivClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            status: 1,
            statusText: "statusText",
            errors: [
                { message: "message", code: "code" },
                { message: "message", code: "code" },
            ],
        };
        server
            .mockEndpoint()
            .patch("/publications/publicationId/webhooks/endpointId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhooks.update("publicationId", "endpointId");
        }).rejects.toThrow(Beehiiv.InternalServerError);
    });

    test("delete (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new BeehiivClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};
        server
            .mockEndpoint()
            .delete("/publications/pub_00000000-0000-0000-0000-000000000000/webhooks/ep_0000000000000000000000000000")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.webhooks.delete(
            "pub_00000000-0000-0000-0000-000000000000",
            "ep_0000000000000000000000000000",
        );
        expect(response).toEqual({});
    });

    test("delete (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new BeehiivClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            status: 1,
            statusText: "statusText",
            errors: [
                { message: "message", code: "code" },
                { message: "message", code: "code" },
            ],
        };
        server
            .mockEndpoint()
            .delete("/publications/publicationId/webhooks/endpointId")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhooks.delete("publicationId", "endpointId");
        }).rejects.toThrow(Beehiiv.BadRequestError);
    });

    test("delete (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new BeehiivClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            status: 1,
            statusText: "statusText",
            errors: [
                { message: "message", code: "code" },
                { message: "message", code: "code" },
            ],
        };
        server
            .mockEndpoint()
            .delete("/publications/publicationId/webhooks/endpointId")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhooks.delete("publicationId", "endpointId");
        }).rejects.toThrow(Beehiiv.NotFoundError);
    });

    test("delete (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new BeehiivClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            status: 1,
            statusText: "statusText",
            errors: [
                { message: "message", code: "code" },
                { message: "message", code: "code" },
            ],
        };
        server
            .mockEndpoint()
            .delete("/publications/publicationId/webhooks/endpointId")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhooks.delete("publicationId", "endpointId");
        }).rejects.toThrow(Beehiiv.TooManyRequestsError);
    });

    test("delete (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new BeehiivClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            status: 1,
            statusText: "statusText",
            errors: [
                { message: "message", code: "code" },
                { message: "message", code: "code" },
            ],
        };
        server
            .mockEndpoint()
            .delete("/publications/publicationId/webhooks/endpointId")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhooks.delete("publicationId", "endpointId");
        }).rejects.toThrow(Beehiiv.InternalServerError);
    });

    test("test (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new BeehiivClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            data: { key: "value" },
            event_timestamp: 1666800076,
            event_type: "post.sent",
            uid: "test_00000000-0000-0000-0000-000000000000",
        };
        server
            .mockEndpoint()
            .get(
                "/publications/pub_00000000-0000-0000-0000-000000000000/webhooks/ep_0000000000000000000000000000/tests",
            )
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.webhooks.test(
            "pub_00000000-0000-0000-0000-000000000000",
            "ep_0000000000000000000000000000",
        );
        expect(response).toEqual({
            data: {
                key: "value",
            },
            event_timestamp: 1666800076,
            event_type: "post.sent",
            uid: "test_00000000-0000-0000-0000-000000000000",
        });
    });

    test("test (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new BeehiivClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            status: 1,
            statusText: "statusText",
            errors: [
                { message: "message", code: "code" },
                { message: "message", code: "code" },
            ],
        };
        server
            .mockEndpoint()
            .get("/publications/publicationId/webhooks/endpointId/tests")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhooks.test("publicationId", "endpointId");
        }).rejects.toThrow(Beehiiv.BadRequestError);
    });

    test("test (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new BeehiivClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            status: 1,
            statusText: "statusText",
            errors: [
                { message: "message", code: "code" },
                { message: "message", code: "code" },
            ],
        };
        server
            .mockEndpoint()
            .get("/publications/publicationId/webhooks/endpointId/tests")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhooks.test("publicationId", "endpointId");
        }).rejects.toThrow(Beehiiv.InternalServerError);
    });
});
