/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { mockServerPool } from "../mock-server/MockServerPool";
import { BeehiivClient } from "../../src/Client";

describe("Workspaces", () => {
    test("identify", async () => {
        const server = mockServerPool.createServer();
        const client = new BeehiivClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            data: {
                id: "work_00000000-0000-0000-0000-000000000000",
                name: "Bruce's Hiiv",
                owner_email: "bruce.wayne@wayneenterprise.com",
            },
        };
        server
            .mockEndpoint()
            .get("/workspaces/identify")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.workspaces.identify();
        expect(response).toEqual({
            data: {
                id: "work_00000000-0000-0000-0000-000000000000",
                name: "Bruce's Hiiv",
                owner_email: "bruce.wayne@wayneenterprise.com",
            },
        });
    });
});
