/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type PublicationsGetRequestExpandItem =
    | "stats"
    | "stat_active_subscriptions"
    | "stat_active_premium_subscriptions"
    | "stat_active_free_subscriptions"
    | "stat_average_open_rate"
    | "stat_average_click_rate"
    | "stat_total_sent"
    | "stat_total_unique_opened"
    | "stat_total_clicked";

export const PublicationsGetRequestExpandItem = {
    Stats: "stats",
    StatActiveSubscriptions: "stat_active_subscriptions",
    StatActivePremiumSubscriptions: "stat_active_premium_subscriptions",
    StatActiveFreeSubscriptions: "stat_active_free_subscriptions",
    StatAverageOpenRate: "stat_average_open_rate",
    StatAverageClickRate: "stat_average_click_rate",
    StatTotalSent: "stat_total_sent",
    StatTotalUniqueOpened: "stat_total_unique_opened",
    StatTotalClicked: "stat_total_clicked",
} as const;
