/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type PublicationsGetPublicationsRequestOrderBy = "created" | "name";

export const PublicationsGetPublicationsRequestOrderBy = {
    Created: "created",
    Name: "name",
} as const;
