/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Beehiiv from "../../../index";

export interface AutomationJourneysCreateResponse {
    data?: Beehiiv.AutomationJourney;
}
