// This file was auto-generated by Fern from our API Definition.

export const AutomationJourneysGetRequestStatus = {
    InProgress: "in_progress",
    Completed: "completed",
    ExitedEarly: "exited_early",
    All: "all",
} as const;
export type AutomationJourneysGetRequestStatus =
    (typeof AutomationJourneysGetRequestStatus)[keyof typeof AutomationJourneysGetRequestStatus];
