/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Beehiiv from "../../../../index.js";

/**
 * @example
 *     {
 *         name: "Gold Tier",
 *         description: "Our premium tier with exclusive benefits",
 *         prices_attributes: [{
 *                 currency: "usd",
 *                 amount_cents: 500,
 *                 enabled: true,
 *                 interval: "month",
 *                 interval_display: "Monthly",
 *                 cta: "Subscribe Now",
 *                 features: ["Exclusive content", "Ad-free experience", "Priority support"]
 *             }]
 *     }
 */
export interface PostPublicationsPublicationIdTiersRequest {
    name: string;
    description?: string;
    prices_attributes?: Beehiiv.TierPricesAttributesItem[];
}
